### ISSUE TITLE
Cook County information assistance

### ISSUE THREAD

**Issue by KathyLynch** [City-Bureau/city-scrapers#138]
Provided a number of Comment markups to the Google Sheet to provide notes or additional info (under Cook County Webmaster).
If there are additional items that we can assist with in providing feeds/api or other sources directly, happy to help save some scraping time. There are some items that we have in development or consideration already.
Please feel free to let us know.
You can also email us at open.data@cookcountyil.gov.
Thanks and hope we can assist in moving some of this info forward for you.

**Comment by diaholliday** [comment]
Thanks for the help and suggestions, Kathy. We'll definitely be in touch as the project progresses, and place feel free to weigh in any time.

**Comment by eads** [comment]
@KathyLynch this is awesome. We'd love to see you at the [Design-A-Thon](http://www.citybureau.org/design-a-thon) if you or a colleague to swing by.

**Comment by diaholliday** [comment]
@KathyLynch Is there any further info available re: when the Cook County RSS feed might be up and running?

**Comment by r-wei** [comment]
The cook_county spider works for now, closing this issue.
