### ISSUE TITLE
code tests for geocoder

### ISSUE THREAD

**Issue by eads** [City-Bureau/city-scrapers#145]
related to #143 -- validated geocodes could be part of these tests, or input / expected values could be found independently. 

Currently using [this library](https://github.com/duydo/python-mapzen), but it doesn't appear it's going to play nice with betamax/requests, so it might be worth just using regular old requests and the mapzen endpoint, or being good citizens and adding mapzen to Python Geocoder.

**Comment by easherma** [comment]
@r-wei can you clarify/update if the current geocoder pipeline has any tests implemented?

**Comment by r-wei** [comment]
There are no tests

**Comment by easherma** [comment]
Okay, thanks for clarifying! 

We might want to consider cleaning up the repo or I could benefit from an explanation of how far along the project did get towards testing (there is some code scattered around that seems to be related) and whether I should connect the dots on what was put together previously or start from scratch. 

As of tonight I am beginning to work on an alternate geooding implementation, but not being able to easily test it is going to slow the process.

**Comment by jim** [comment]
@easherma We have tests for most (all?) of the spiders, but not any of the other classes such as middlewares. Feel free to add a file under `tests` and put any tests for your implementation there. We'd like to avoid dependencies on other files and external resources as much as possible.

We have used betamax to stub out HTTP requests in the past, so feel free to use that if you think it will help. You can see its use in [the tests for some of the file generation tasks](https://github.com/City-Bureau/documenters-aggregator/blob/5fbca7d246a3c9fd089ebf442839a40e148ac368/tests/test_tasks.py).

**Comment by easherma** [comment]
Jim,

Thanks for clarifying. I'll see what I come up with. We should consider
cleaning up the master repo though to strip out things not being used in
the current version to avoid confusion for future devs. I understand this
isn't a large priority at the moment and would be tedious. We could also
clean up the files folder to be a little more clear on what could be used
for what. I can file either of these as issues, but I understand they may
not be priorities at the moment.

**Comment by jim** [comment]
I am 100% in favor of cleanup of all types. Please file issues with specific tasks you think we should undertake so we can prioritize and make them happen!

**Comment by easherma** [comment]
This is relevant for #249

**Comment by easherma** [comment]
[I did write a basic test](https://github.com/City-Bureau/city-scrapers/blob/249-geocode-branch/tests/test_geocode_pipeline.py)

**Comment by pjsier** [comment]
Closed by. #487
