### ISSUE TITLE
Reuse HTTP connection to ocd.datamade.us

### ISSUE THREAD

**Issue by jim** [City-Bureau/city-scrapers#183]
The `cityclerk` spider makes a lot of requests to `ocd.datamade.us`:

```
2017-11-17 12:49:47 [urllib3.connectionpool] DEBUG: Starting new HTTPS connection (1): ocd.datamade.us
```

Ideally, we can re-use a single HTTP connection to reduce the overhead on both ends.

**Comment by bergren2** [comment]
Looks like this was fixed by c15187ad29d3e7bb364ed0b52e4362f781743446?

**Comment by jim** [comment]
@bergren2 I think that commit helps by reducing the number of requests, but (and I haven't verified this) I think we're still opening a lot of HTTP connections.

**Comment by bonfirefan** [comment]
@jim so this was an issue when writing the spider - it seemed relatively simple using urllib's requests, and a bit more overkill with Scrapy. Would this be solved by using [Sessions](http://docs.python-requests.org/en/master/user/advanced/)? Apparently Scrapy uses twisted's HTTPClient which isn't persistent.

**Comment by jim** [comment]
@bonfirefan I think that using a `Session` object with `requests` would work. It also looks like support for [persistent connections was added to Twisted](https://twistedmatrix.com/documents/17.5.0/web/howto/client.html#http-persistent-connection) at some point, but I have no idea how difficult that would be to use within Scrapy.

I'm going to mark this as a "nice-to-have", since this isn't currently causing any problems. But I imagine that whatever we figure out here may be useful for the other API wrapper spiders that we have or will have eventually in the system.

**Comment by pjsier** [comment]
This spider is scraping from Legistar directly now, so we should be good here
