### ISSUE TITLE
new spider request: Chicago teachers pension fund

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#191]
Up for grabs. See [docs on contributing a spider](https://city-bureau.github.io/city-scrapers/03_contribute.html). Site to scrape: http://www.ctpf.org/general_info/boardmeetings.htm

**Comment by r-wei** [comment]
Non-coding tasks:
- [ ] should these events be update manually or by a spider?
- [ ] if manual, add these events to airtable

**Comment by easherma** [comment]
working on this one, PR to follow

**Comment by jim** [comment]
@easherma As we discussed, please hold off on this until your other PR (#288) has been fully completed.

**Comment by r-wei** [comment]
@nickdevlin is working

**Comment by diaholliday** [comment]
@nickdevlin just wanted to check in on this, are you still working on this spider or should we put back out to the group?

**Comment by r-wei** [comment]
resolved by #411
