### ISSUE TITLE
new spider request: cook county housing authority

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#192]
Up for grabs. See [docs on contributing a spider](https://city-bureau.gitbooks.io/documenters-event-aggregator/contribute-a-spider.html). Site to scrape: http://thehacc.org/events/

**Comment by r-wei** [comment]
Non-coding tasks:
- [ ] should these events be update manually or by a spider?
- [ ] if manual, add these events to airtable

**Comment by emmanuellyautomated** [comment]
currently working on this one!

**Comment by diaholliday** [comment]
Hey @emmanuellyautomated, are you still working on this spider? Would love to add it to the set. Just wanted to check in while it's on my mind. We can re-assign it if you'd rather hand it off.

**Comment by diaholliday** [comment]
hey @emmanuellyautomated just wanted to check in on this, are you still working on this spider or should we put back out to the group? No worries if you have to let it go—I'll plan to go ahead and re-assign it if I don't hear back from you by May 4.

**Comment by diaholliday** [comment]
@emmanuellyautomated I appreciate you work and time on this but I need to go ahead and re-assign this spider so we can start sending Documenters out to these meetings on a more regular basis.

**Comment by r-wei** [comment]
@cherdeman is working

**Comment by r-wei** [comment]
resolved by #339

**Comment by diaholliday** [comment]
Can we add this to the Scraper Status section too? @pjsier
