### ISSUE TITLE
New spider request: Metra board of directors

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#193]
Up for grabs. See [docs on contributing a spider](https://city-bureau.gitbooks.io/documenters-event-aggregator/contribute-a-spider.html). Site to scrape: https://metrarail.com/about-metra/leadership/board-meetings

**Comment by meshulam** [comment]
I started on this at Logan Square Hack Night, PR forthcoming!

**Comment by r-wei** [comment]
Resolved by #240
