### ISSUE TITLE
Cook County ids are not using the new format

### ISSUE THREAD

**Issue by jim** [City-Bureau/city-scrapers#195]
<img width="1147" alt="screen shot 2017-11-28 at 6 11 24 pm" src="https://user-images.githubusercontent.com/3331/33351060-9a4f5eba-d467-11e7-83c2-0eaa27d6de9e.png">

We need a simple fix to make [this code](https://github.com/City-Bureau/documenters-aggregator/blob/master/documenters_aggregator/spiders/cook_county.py#L74) work like similar code in the other spiders.

**Comment by milti** [comment]
@r-wei should i look at this one next?

**Comment by jim** [comment]
@milti Feel free to take a stab at this! If you have any questions, please let us know.

**Comment by bonfirefan** [comment]
@milti, @r-wei see if this is no longer an issue, we took out the custom id_parser in the latest datetime branch update

**Comment by milti** [comment]
willdo. thanks.

**Comment by r-wei** [comment]
This issue will be resolved in PR #245

**Comment by r-wei** [comment]
resolved by #245
