### ISSUE TITLE
Add "CAPS" classification to airtable display name

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#196]
I think this is a backend/scraper issue not airtable specifically (please correct me if I'm wrong):

Can we add "CAPS" to tall Chicago Police Department listings that feature "CAPS community event" in the classification field? i.e. the display name would say "Chicago Police Department - CAPS Beat Meeting: 1135" or "Chicago Police Department - CAPS Beat 2423 Community Relations Meeting"

It would also be great if we could standardize all of the CAPS beat meetings to a single format (much less of a priority tho). Right now the beat meetings show up in different orders but contain the same information (see above examples). Would be great if they could all say "[Chicago Police Department] - CAPS [Beat #]" or something similar

**Comment by r-wei** [comment]
resolved by #294
