### ISSUE TITLE
il_pubhealth spider doesn't parse locations

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#201]
location name and address are both ''.

**Comment by vincecima** [comment]
@r-wei looking into this now and it appears that the sites lists multiple locations for each event. The OCD format doesn't appear to allow for > 1 location for a meeting? Should we make a best effort to parse and save the first location?

**Comment by r-wei** [comment]
Hm, my guess would be to pick the Chicago location whenever possible. @diaholliday, what do you think? There are multiple locations here: http://www.dph.illinois.gov/events

**Comment by r-wei** [comment]
resolved by #303
