### ISSUE TITLE
Mapzen is shutting down :(

### ISSUE THREAD

**Issue by jim** [City-Bureau/city-scrapers#207]
https://mapzen.com/blog/shutdown/

There are [some alternatives](https://mapzen.com/blog/migration/#mapzen-search) listed on their [migration guide](https://mapzen.com/blog/migration/). We'll need to find a replacement that provides lat/long as well as community area.

cc @r-wei

**Comment by easherma** [comment]
Oh dear! That is sad news. I’d be happy to help with this; I think our best
bet is incorportating the python geocoder library so that we can easily
switch between options.

**Comment by jim** [comment]
@easherma Agree that moving to something that isn't provider-specific is a good idea as long as we can get the data we need!

**Comment by easherma** [comment]
@jim wanna check in about this soon? I had started a pull request that was geocoder agnostic that I could dive back into but I'm not sure if this is still a priority?

**Comment by bonfirefan** [comment]
I'm assuming this is a priority - it sounded like you were doing some structural reworking by creating a new pipeline? Would it work in interim to call work in the geocoder package in the existing geocoder.py file?

**Comment by easherma** [comment]
I did open a pull request that began this work. Testing is a little
convoluted...I think with a sit down between rebecca and I we could
probably wrap up the rest of that refactoring in an hour or two

**Comment by jim** [comment]
Closing in favor of #249.
