### ISSUE TITLE
Move to Pipenv for managing dependencies

### ISSUE THREAD

**Issue by jim** [City-Bureau/city-scrapers#211]
[Pipenv](https://docs.pipenv.org) looks like the future of packaging in Python, at least from an outsider's perspective. We might want to consider moving to it for this project, as it seems to have simpler workflows and fewer steps for new folks to master.

**Comment by easherma** [comment]
Looks pretty groovy! We can also flesh out Docker support and document how
to use that too. Maybe even do both? I have no strong preference or
perspective but I'm hoping to dig in with some commits soon and would have
more of an opinion after that.

**Comment by jim** [comment]
@easherma I [updated the deployment docs a bit](d12e9872), which starts to get into how we're using Docker and created an issue to track [adding documentation for local development using Docker](https://github.com/City-Bureau/documenters-aggregator/issues/212).

**Comment by pjsier** [comment]
Closed by #404
