### ISSUE TITLE
Airtable "display name" column

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#213]
It looks like the Airtable "display name" column doesn't allow for manual input because it's a formula. I'm working on uploading some PDF meetings for 2018 but I"m unable to fill in info in any columns that are set in formula mode. Any suggestions for how to get around this?

**Comment by diaholliday** [comment]
Correction: After messing around with the columns for a bit I see that the formula tables can accept manual input by adding values in the columns built into the formula but there's another problem I'm seeing, there's something going on in the times or timeszones that is putting the meetings off by several hours. A good number of the meeting start times throughout the aggregator are at 10pm, 11pm, etc (i.e. incorrect times). I can input meetings from the PDFs but those meeting times are being thrown off by what I think may be the timezone formatting.
![screen shot 2018-01-06 at 12 24 25 am](https://user-images.githubusercontent.com/4017450/34637287-660a21ce-f278-11e7-931a-22135d76b809.png)

**Comment by jim** [comment]
@diaholliday Is this still a problem? I can't recall if we addressed this or not.

**Comment by diaholliday** [comment]
Yep, I believe we're all set on this one.
