### ISSUE TITLE
Assignment application formatting

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#217]
@jim two things I just noticed on the assignment application form. In addition to auto-splitting assignments into multiple entries when multiple assignments are selected, i.e. one for live-tweeting, one for submit meeting notes, etc, and making the url "citybureau.org/applications" can we also:

1. switch the two header lines so the department name is the larger/bold one and the type of meeting is on the line below in smaller type?

2. change the selection box from a square outline to a solid box that fills the space

3. Change the "location" line to the address
![screen shot 2018-01-08 at 8 14 12 pm](https://user-images.githubusercontent.com/4017450/34702014-0f2c139a-f4b1-11e7-95ac-34c5562e3da5.png)

4. We can cut the "terms and conditions" checkbox entirely and replace it with "I agree to attend my assigned meeting at the given day and time, and stay for its duration" and another checkbox for "I agree to read all emailed instructions and submit my documentation to City Bureau within 24 hours of the end of my assigned meeting" and another checkbox for "I understand that Documenters are independent contractors and that I am responsible for all taxes associated with this income.”
![screen shot 2018-01-09 at 10 49 18 am](https://user-images.githubusercontent.com/4017450/34732399-c5915356-f52a-11e7-9610-2ea4216282e4.png)

**Comment by jim** [comment]
Also, add a label to the description.

**Comment by jim** [comment]
Add a banner at the bottom that tells users to scroll down after selecting a meeting.
