### ISSUE TITLE
Board of Education Description Field

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#224]
The Chicago Board of Education spider currently doesn't have description info coming through—can we add this text to that field?

"The Chicago Board of Education is responsible for the governance, organizational and financial oversight of Chicago Public Schools (CPS), the third largest school district in the United States of America."

**Comment by r-wei** [comment]
I'm not seeing this spider in the repo anymore. @jim , @bonfirefan , was it removed for some reason?

**Comment by bonfirefan** [comment]
Is it not [/documenters_aggregator/spiders/chi_schools.py](https://github.com/City-Bureau/city-scrapers/blob/master/documenters_aggregator/spiders/chi_schools.py) ?

**Comment by r-wei** [comment]
Ah there it is. Thanks @bonfirefan

**Comment by bonfirefan** [comment]
Phew! I got worried that it had been somehow deleted in one of the many reworkings we did 😅

**Comment by diaholliday** [comment]
Is there an easy way for me to add descriptions to scrapers? I've seen a few that could use some brief additions and/or tweaks.
