### ISSUE TITLE
New Spider Request: CPS Local School Council excel sheet 

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#229]
This is all the city currently has on the LSC's in Chicago but they'll have more once the committees elect new officials in July. In the meantime, can we add these meetings via scraper? Or would it be best to do by hand (there are quite a few).
[LSC Meetings 2018.xlsx](https://github.com/City-Bureau/documenters-aggregator/files/1679763/LSC.Meetings.2018.xlsx)

**Comment by diaholliday** [comment]
Just wanted to quickly check in on this issue while LSCs are on my mind. Is this the best way to bump issues in Github? I'm mostly curious whether this is best as a spider or a manual input. There are lots of meetings the on the sheet but I could help fill in the other info if it can be a spider (i.e. description, address, community area, etc)

**Comment by r-wei** [comment]
Having the tags "good first issue" and "help wanted" makes them more visible already. Spreadsheets are generally easy for spiders to scrape. Description and address are needed, but community area can be gotten from a geocoder.

**Comment by jim** [comment]
@diaholliday Can we make the spreadsheet a Google Sheet instead? That way we can handle it like the ward nights.

**Comment by diaholliday** [comment]
@jim it should all be here in the first tab: https://docs.google.com/spreadsheets/d/1uzgWLWl19OUK6RhkAuqy6O6p4coTOqA22_nmKfzbakE/edit#gid=1962457190

**Comment by bonfirefan** [comment]
@cherdeman is writing tests for this!
