### ISSUE TITLE
New Spider Request: CTA red line extension meetings

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#232]
@r-wei came across this sign on the train but I've also confirmed with CTA that this site will the one used for all Red Line extension meeting announcements going forward: http://www.transitchicago.com/news_initiatives/planning/rlx/whatsnew.aspx

Train sign:
![20180131_075726](https://user-images.githubusercontent.com/4017450/35643018-93854c02-068a-11e8-91a9-7463de027619.jpg)

**Comment by bonfirefan** [comment]
So actually it looks like all capital project related meetings are posted under their [own subpages](http://www.transitchicago.com/news_initiatives/planning/). Long term it may be better to scrape all sup-projects posted with a "What's New" page for anything event-looking, but even longer term it could be better to request those events be posted on the main event portal - I can look into both.

**Comment by r-wei** [comment]
Non-coding tasks:
- [ ] should these events be update manually or by a spider?
- [ ] if manual, add these events to airtable

**Comment by bonfirefan** [comment]
Ok - the new link is now https://www.transitchicago.com/redeis/whats-new/
What we can do is add the link to the start_urls list and add separate parsing functions for this link.

**Comment by r-wei** [comment]
@bonfirefan , looks like this site doesn't have events anymore..? Maybe we should repurpose this issue into a non-coding/journalist task about building and maintaining a relationship/open line of communication with capital projects at CTA.

**Comment by bonfirefan** [comment]
New meetings are up at https://www.transitchicago.com/rpm/whatsnew/
It will probably be necessary to get in contact with RPM@transitchicago.com and do the same for other long term capital projects.
