### ISSUE TITLE
Directions for non-coders?

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#233]
@cgreim brought up a great point last night re: the addition of README language that can help guide non-coders to non-coding jobs/needs within the project. I think this is a great idea and would be happy to write that out and post for review/addition. 

In the meantime, does anyone have thoughts on this? My initial thoughts are that there are needs such as researching meetings (and possibly departments) that are not currently included in the aggregator, (eventually) user testing parts of the system, researching potential partner organizations and/or groups that could benefit from the tool, etc.

**Comment by r-wei** [comment]
We should definitely make non-coder contributions more apparent. I think non-coders could work on #219 -- a group of non-coders could start by vetting a couple of meeting sources, and then build out a resource for "how to determine if a meeting should be scraped or manually input".

They could also publish some things they learn about how different local gov orgs interact, host meetings, etc.

**Comment by cgreim** [comment]
🙌 all this sounds good.

I'll add, I think there's some value in trying to organize the non-coding work in a similar way to the coding work. 

One way we could do this is to use a label on issues that indicates they're things non-coders could work on (like #219 -- or a ticket based on #219 that breaks out the suggestions @r-wei made above) and then include some copy in the README that encourages non-coders to jump in and directs them to those labeled issues (I think we can link directly to a filter that only shows issues with a particular label). 

Anyone can add more non-coding tasks as Github issues as they come up, and we won't have to revise the README as frequently. 

I also recognize Github might be new for folks (especially non-coders), so maybe we can include a note about how to get help if you need it -- and if we see common stumbling points can put together a guide or FAQs or something.

**Comment by r-wei** [comment]
We have some basic instructions in the read me, so I'll close this issue. If we get feedback from interested non-coders on improvements, we can re-open this issue or make a new one.
