### ISSUE TITLE
ward nights spider is broken

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#234]
Errors:
```
[ward_night] TypeError("descriptor 'strftime' requires a 'datetime.date' object but received a 'str'",)
[ward_night] AttributeError("'datetime.datetime' object has no attribute 'upper'",)
[ward_night] NameError("name 'timezone' is not defined",)
[ward_night] NameError("name '_naive_datetime_to_utc' is not defined",)
```

**Comment by jim** [comment]
@r-wei Turns out these were from me running the code locally. Sorry about the confusion.

<img width="387" alt="screen shot 2018-02-06 at 8 56 09 pm" src="https://user-images.githubusercontent.com/3331/35896116-505e343e-0b80-11e8-8a6f-9f52cb8682c7.png">
