### ISSUE TITLE
Build a pipeline for local development

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#236]
To make things more user-friendly for newcomers, we want a pipeline that writes spider output to a local file. So, when someone calls `scrapy crawl my-spider-name`, they get all of the scraped items in a local, human-readable file.

Some things that probably need to be done for this:
- Create a pipeline for local development
- Register the pipeline in pipelines/__init__.py
- Turn the pipeline on in settings.py
- Create a folder for scraped results and add it to gitignore
- Figure out what constitutes human-readable for newcomers

About scrapy pipelines: https://www.youtube.com/watch?v=MtU4xuI8v4c&index=3&list=PLyCZ96_3y5LXfPVZkHjhHRuIWhcjvCyQA  (if you watch the video, feedback is welcome!)

**Comment by easherma** [comment]
👍👌

**Comment by jim** [comment]
Build tackled by @bonfirefan in #251.

**Comment by bonfirefan** [comment]
Resolved by #251
