### ISSUE TITLE
Establish naming conventions

### ISSUE THREAD

**Issue by easherma** [City-Bureau/city-scrapers#237]
There has been a change to the project name, at least public facing, that brings up the issue of consistent names for things in order to avoid confusion or excess refactoring later.

I think it makes sense that the project could have a different public facing name. This should be geared towards whatever makes the most sense for engagment.

When it comes to aspects of the project development, I’d suggest that we try to be as explicit as we can.

For instance, calling this documenters_aggregator is decent, becuase what this app does is aggregate public meeting data so that documenters know whete to go.

But really its just a public meetings aggregator. It doesn’t even really scrape, since we rely on Scrapy for that.

This is more of a stub just to get the conversation going.

**Comment by jim** [comment]
I think we're pretty set on City Scrapers for the time being.
