### ISSUE TITLE
Help with Airtable Formula + New Column

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#244]
Alright, I've tried giving this a go myself but can't seem to find the right formula. I'd like to create an Airtable column that reads the "Application" column and checks an "eligible" box if a Documenter has both an application AND a training checked in the system. 

I made the eligibility column as a formula. Ideally, it'll read if a person has an application in then checks to see if they have a skills survey, orientation, notetaking, interview, social media, photography, audio recording, open meetings act, FOIA (OR) newsletter box checked.

![screen shot 2018-02-12 at 6 32 58 pm](https://user-images.githubusercontent.com/4017450/36127578-dbb2653a-1023-11e8-8dcd-fe1812c0b15d.png)

**Comment by r-wei** [comment]
@diaholliday   I've made a column called is_eligible that is 1 if they have application and at least one of the trainings, 0 if they don't. 

Working on turning the 1's and 0's into "yes" and "no"... Or should they be something else?

In airtable, should we be using the "application" column or the "application complete" column?

**Comment by diaholliday** [comment]
Thanks! Yes/No would be ideal. It's the "Application" column

**Comment by r-wei** [comment]
np, take a look now and if it's good feel free to close the issue.

**Comment by diaholliday** [comment]
Yep, that's perfect, thanks. Also took a look at your formula—that's super helpful to see.

**Comment by r-wei** [comment]
great, yeah, you can add/remove training columns there if you want
