### ISSUE TITLE
Spider Needed: Metropolitan Water Reclamation District of Greater Chicago

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#257]
This one looks pretty straightforward and uses the same system as Chicago City Council: https://mwrd.legistar.com/Calendar.aspx

**Comment by nickjordan** [comment]
Looking into this.

**Comment by diaholliday** [comment]
Thanks @nickjordan! Any updates so far?

**Comment by diaholliday** [comment]
Btw here's some background on why we're interested in the MWRD meetings: https://www.bettergov.org/news/shaw-time-for-a-watchdog-at-metropolitan-water-district?rf=head&eType=EmailBlastContent&eId=e6dc14d0-782b-4e2b-993e-67ec1f88f1d3

**Comment by eads** [comment]
Waaay back when, I met a guy running for MWRD president and he made no bones that it's a way into the political machine.

**Comment by easherma** [comment]
True story. A little way back when, when I was more involved in local
politics, I got offered a 'chance' to run for one of those positions.

**Comment by diaholliday** [comment]
Anyone interested in building this scraper if @nickjordan can't? I'd love to start sending Docs to them going forward. @nickjordan still all yours if you've already started it and/or want to keep working on it.

**Comment by easherma** [comment]
@diaholliday I can grab this one, it's been some time and we haven't heard from @nickjordan , and there is a soft spot in my heart for the MWRD. :-)

**Comment by diaholliday** [comment]
Woot! Thanks, I'm v curious about those meetings. Can't wait to send Documenters to them.

**Comment by easherma** [comment]
MWRD uses Legistar, relevant issues #33, #74

**Comment by easherma** [comment]
[PR opened](https://github.com/City-Bureau/city-scrapers/pull/288)

**Comment by diaholliday** [comment]
hey @easherma can you update me on the status of this PR? I'm going through the April milestone list to see if I can help move anything forward. No worries, if you're still working on it!

**Comment by easherma** [comment]
The spider works but tests aren't written yet.

**Comment by bonfirefan** [comment]
Completed with #359
