### ISSUE TITLE
new spider: cook_electoral

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#259]
The site we were scraping is down: https://www.cookcountyclerk.com/elections/electoralboard/Pages/default.aspx

We need to find the url where the Cook County Electoral Board is keeping their events, and write a spider for that site.

**Comment by vertigokidd** [comment]
FYI, here is where the board publishes its meeting info: https://www.cookcountyclerk.com/service/board-meetings

**Comment by easherma** [comment]
I'm double-checking with some contacts, but I believe the situation here is as follows:

* The electoral board meets around upcoming elections, including primaries. They mainly exist to hear objections and make decisions about candidates running for cook county office. I don't believe they meet on a regular basis but I am confirming this. 
* Meeting notices are posted here as pdfs: https://www.cookcountyclerk.com/service/electoral-board
* Past case info is here: https://electoralboard.cookcountyclerk.com/#!/case?electionId=61 (does not appear to have meeting dates).

**Comment by r-wei** [comment]
Future meetings are listed here: https://www.cookcountyclerk.com/service/board-meetings

**Comment by noahkconley** [comment]
I'll take this!

**Comment by bonfirefan** [comment]
Closed by #389
