### ISSUE TITLE
Fix travis validation pipeline

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#260]
We changed the events schema so that start times and end times should be datetime objects instead of strings. We need to update the travis validation pipeline to reflect this. It also seems to error out if there is more than one spider to validate.

**Comment by pjsier** [comment]
It looks like this was fixed by #245?

**Comment by r-wei** [comment]
yep :)

**Comment by bonfirefan** [comment]
Just for future note, something that @jim and I briefly talked about - the conversion to naive date is using the `_naive_datetime_to_tz` function, which defaults to the Chicago/America timezone.
