### ISSUE TITLE
Scraper status at-a-glance

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#265]
Could we come up with a way to see which scrapers are broken/working at-a-glance? A real-time status would be ideal but I could also see this being a daily check that displays the status of each scraper currently in operation (i.e. working, broken, needs attention, etc). 

This is the sort of tool that would be ideal for import to the platform down the line—if there's a way to make a working model in the meantime, that'd be ideal. Currently, it's difficult for the Documenters Manager to see if a meeting is not being imported, because the related scraper doesn't show up as broken (it just doesn't show up in the queue at all).

**Comment by pjsier** [comment]
I can take a stab at this, and I'm summarizing a conversation with @diaholliday on Slack here. The current idea is to list each scraper in the README next to an SVG icon indicating its current status, similar to the Travis CI status badge.

The icons can be stored on S3 with filenames based on the scraper name, and we can update each scraper icon automatically after they run. We'll need to find the most straightforward way of detecting whether a scraper failed or needs attention (potentially through the ECS task state, or through added exception handling on Scrapy) and call a Lambda function to update the icon either way.

**Comment by diaholliday** [comment]
This all sounds great! My only request for now is that the display names for each scraper be as close as possible to the real department name (or easy to read abbreviations). Some of the scraper filenames are closer to shorthand—it'd be great if these display names were easy to discern at a glance.

**Comment by pjsier** [comment]
Definitely! I didn't clarify in the issue, but I was thinking it would look something like this. The scraper name would be mostly for the filename

### Scraper Status

| Scraper | Status |
|-------------------------------------------|------|
| Chicago Parks District                    | ![Build Status](https://travis-ci.org/City-Bureau/city-scrapers.svg?branch=master) |
| Chicago Public Schools Board of Education | ![Build Status](https://travis-ci.org/City-Bureau/city-scrapers.svg?branch=master) |

**Comment by diaholliday** [comment]
Yesss, this is great.

**Comment by jim** [comment]
This is up and running!
