### ISSUE TITLE
Michigan Public Meetings Aggregator (list)

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#292]
Claim spiders by adding a comment to the "Who is coding" column with your name. Add links to calendar pages and suggest new departments via comment in the appropriate columns.

https://docs.google.com/spreadsheets/d/1fxbJNhwFUDKTvSARvHZkQV01FsBw5638IZr32q3zXKM/edit#gid=1418551062

**Comment by hampelm** [comment]
Just to confirm, is the current list now at https://docs.google.com/spreadsheets/d/1Uu9FmcQAy8AXhBR2bj84LbSdlfgMNNroa9P89rsDJSQ/edit#gid=1214169297 ?

**Comment by diaholliday** [comment]
Correct @hampelm! That is the current list.

**Comment by pjsier** [comment]
Moved all new scrapers to GitHub issues
