### ISSUE TITLE
Detroit Board of Education (DPSCD)

### ISSUE THREAD

**Issue by jmcbroom** [City-Bureau/city-scrapers#296]
New scraper for the DPSCD Board of Education from http://detroitk12.org/board/meetings/

**Comment by vincecima** [comment]
@jmcbroom if no one else has claimed this one, I would love to take a shot.

**Comment by vincecima** [comment]
@jmcbroom I just saw the spreadsheet mentioned in (https://github.com/City-Bureau/city-scrapers/issues/292). Happy to take a shot at something else, let me know either way.

**Comment by jmcbroom** [comment]
@vincecima please, feel free! I can grab a different one
