### ISSUE TITLE
Scraper status Lambda function not updating on error

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#301]
Some spiders have been failing, but the status Lambda didn't update their icons at all. I'm guessing this is because the status isn't listed as 'STOPPED' (https://github.com/City-Bureau/city-scrapers/blob/master/deploy/scrapers_status.py#L45), but there are also some other things it would throw errors for that should show up in the logs

**Comment by r-wei** [comment]
@jim @pjsier I fixed the json decode error with chi_police, but it hasn't been merged in yet. It's on an open PR. Just fyi in case you're looking at individual spiders
