### ISSUE TITLE
New Spider Request: CPS Community Action Council

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#318]
Link to the site is here: http://cps.edu/FACE/Pages/CAC.aspx

Looks like a pretty straightforward spider with one main exception—meetings aren't listed individually, they're listed on a recurring schedule:
![screen shot 2018-04-23 at 6 36 31 pm](https://user-images.githubusercontent.com/4017450/39158392-67f0f952-4725-11e8-8b41-695fd1f99cd4.png)

**Comment by brettvanderwerff** [comment]
Can you assign this to me?. I am an open source newbie, but have some scraping experience with my own pet projects. I'm still looking at your code base to figure out how things run, but would like the chance to try this if you are willing to give it to me. Thank you.

**Comment by diaholliday** [comment]
Hi @brettvanderwerff! It's all yours. I'm pretty sure no one has started it yet. Are you able to create pull requests? Let me know if you need a certain level of access that you don't already have. @jim @bonfirefan or I can help you get set up.

**Comment by brettvanderwerff** [comment]
Do you wan't me to put in the pull requests as soon as I set up the new branch to let people know it is a work in progress?

**Comment by diaholliday** [comment]
I'll wait for @jim or @bonfirefan to let us know what the next best step is. Don't want to tell you the wrong thing.

**Comment by diaholliday** [comment]
Hey @brettvanderwerff I just double-checked procedure on this. This conversation is sufficient as a claim on the spider. No need to start a PR at this point. This spider is all yours!

**Comment by brettvanderwerff** [comment]
Ok thanks I'm starting out on this, I'm new to scrapy, so I'm just getting up to speed on the documentation it might take me a little bit to get up and running. I'll put in a WIP pull request once I have some worthwhile code.

**Comment by bonfirefan** [comment]
@brettvanderweff, my apologies on the delay here! You’ve totally got it, all you need to do to claim an issue is to comment! And yes, whenever you feel at a comfortable point, please do make a pull request for review. We of course won’t merge it in until completion and you’ll be able to continue to make changes.

**Comment by brettvanderwerff** [comment]
I just want to keep the lines of communication open on this and let you know that I am still engaged in this and plugging along. There are a lot of firsts in this one for me.

**Comment by r-wei** [comment]
@brettvanderwerff , thanks for the update. Feel free also to ask questions in slack or show up to an in-person coding session: https://www.citybureau.org/city-scrapers-get-involved (scroll to the bottom for the calendar)

**Comment by r-wei** [comment]
resolved by #330
