### ISSUE TITLE
ImportError: No module named win32api when running spider for the first time on windows.

### ISSUE THREAD

**Issue by brettvanderwerff** [City-Bureau/city-scrapers#321]
I'm using windows 10, python 3.6.3 running in virtual environment (did not do docker).  When setting up for the first time and trying to run a spider I ran into:

ImportError: No module named win32api

It wasnt that big of a deal and went away with installing pywin32 and everything worked fine after that.

I think this is a known issue with scrapy on windows: https://doc.scrapy.org/en/latest/faq.html 

I looked through your documentation and can see you recommenced developing on linux (which I will do moving forward), but regardless this may prevent people who try to run on windows from having something that works "out of the box". I don't see pywin32 in the reqs file.

Sorry if I missed something in the documentation about this. I am extremely new to scrapy and somewhat new to python also.

**Comment by bonfirefan** [comment]
Thanks @brettvanderwerff - are you able to run the test command on windows with `invoke runtests` ? I believe that an incompatibility with `invoke` prevented us from supporting further development on Windows, but we're definitely still interested in resolving that.

**Comment by brettvanderwerff** [comment]
`invoke` does not run on my setup, you can disregard this issue if you are not worried about people running on windows. I did see the windows testing issue in the documentation before posting. Thank you!
