### ISSUE TITLE
Revise Contribution guide to increase visibility into work

### ISSUE THREAD

**Issue by jim** [City-Bureau/city-scrapers#328]
* _New_ Developers should open a `[WIP]` pull request when they start working on an issue so that we can see what is being worked on.
* _Update_ Mention that issues without activity for 30 days may be reassigned or closed (just like we do with PRs).

This came out of a convo with @diaholliday.

cc @r-wei @bonfirefan

**Comment by r-wei** [comment]
resolved by #349
