### ISSUE TITLE
Public site still mentions "documenters-aggregator"

### ISSUE THREAD

**Issue by jim** [City-Bureau/city-scrapers#331]
Our [public documentation site](https://city-bureau.github.io/city-scrapers/) still has a lot of mentions of the old project name.

The files for that site are all found in the `docs` directory of the project. We need to replace all instances of "Documenters Aggregator" with "City Scrapers". The content is all in markdown files and can be previewed in a lot of editors- there will be some styles missing, but that should be enough to see that they are rendering the content properly.

**Comment by thenoelman** [comment]
Has this been corrected already?  I don't see the text "Documenters Aggregator" in any of the .md files within the docs folder.

**Comment by bonfirefan** [comment]
Hey @thenoelman, thanks for taking a look! It does seem like we've removed all mentions of "Documenters Aggregator." I'll close this.
