### ISSUE TITLE
Split out agency name addition into separate pipeline

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#333]
Currently the only reference to the host agency in the event schema is the slug in the ID. That means anything consuming the events has to have a mapping of slugs and agency names and update it each time a new scraper is added. 

The Open Civic Data spec for events supports a `participants` array of people or organizations as [linked entities](https://opencivicdata.readthedocs.io/en/latest/data/event.html#linked-entities). We could update the event schema to require the host organization in the `participants` array as something like this:
```json
{
  "participants": [{
    "note": "Host",
    "entity_name": "Chicago Transit Authority Board",
    "entity_type": "organization",
    "entity_id": "ENTITYID"
  }]
}
```
It doesn't look like much additional work in the scrapers, we could probably [create the OCD IDs](https://opencivicdata.readthedocs.io/en/latest/ocdids.html) in the `genspider` task, and it could simplify handling events data. What do people think?

**Comment by r-wei** [comment]
Hey @pjsier , how is host agency different than the spider's long name? What is a slug?

On a related note, maybe we should have some code that makes it easier to make changes to the events schema. I'll make a separate issue for this.

**Comment by pjsier** [comment]
@r-wei it would be the same thing, but right now it doesn't look like we include that in the output for each event. And for slug I mean something like `chi_transit` for "Chicago Transit Authority Board"

**Comment by pjsier** [comment]
@r-wei ah, I didn't realize it was getting pulled in there. I didn't see it in the output of the feed export in #332, and it's probably because I disabled the Airtable pipeline for testing. I'm fine with leaving it in `agency_name`, but we should probably add that in a more general location. Is there anywhere in particular that you think it makes sense to add that to the item dictionary?
