### ISSUE TITLE
make it easier to change the events schema

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#334]
Currently, in order to change the events schema, the following things must be done (feel free to add to this list):

- update all the spiders
- update docs for [events schema](https://github.com/City-Bureau/city-scrapers/blob/master/docs/06_event_schema.md)
- update [templates](https://github.com/City-Bureau/city-scrapers/tree/master/templates) and test fixtures [1](https://github.com/City-Bureau/city-scrapers/blob/master/tests/files/test_testspider.py.example), [2](https://github.com/City-Bureau/city-scrapers/blob/master/tests/files/testspider.py.example)
- update [travis validation pipeline](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/pipelines/TravisValidation.py)
- update other pipelines as needed

Maybe we should write code so that some of the above can be automated. At the very least, we should have some docs/process around this so it's not just a list of things in my head every time we want to change to the events schema. ^-^

**Comment by pjsier** [comment]
Updated with the `city-scrapers-core` package and pipelines
