### ISSUE TITLE
Are Community Action Council meetings happening in Humboldt Park East?

### ISSUE THREAD

**Issue by rebecca-burwei** [City-Bureau/city-scrapers#337]
According to the [Community Action Council website](http://cps.edu/FACE/Pages/CAC.aspx), there are biweekly events in Humboldt Park East. However, these events don't seem to appear on [Humboldt Park's website](http://www.humboldtparkportal.org/events/). We want to know whether or not these events are happening, and if they are, where they are listed online.

This is a good non-coding issue for someone who wants to do agency-related research and start a relationship/open a line of communication with these organizations.

**Comment by ab1470** [comment]
I just emailed Carl Hurdlik, the contact listed on the CAC website for more information on the biweekly meetings. I will update this when I hear back from him.

**Comment by ab1470** [comment]
Here's Carl's response to my inquiry:
> The HP-East CAC structures their meetings differently than our other 8 CACs.   They meet with the principals of their partner schools once a month and then have a separate meeting with other community stakeholders usually once a month (although it's been less often recently).   They are presenting their plans, partners, and programming this Saturday [May 19th] at our All-CAC Summit if you would like to join us (flier attached) so you can get to meet some of their stakeholders.   Otherwise, their next meeting will probably be Saturday, June 2nd (but that still has to be finalized).

Sounds like the only way to get information about meetings is to reach out to Carl.

**Comment by bonfirefan** [comment]
Thanks for addressing this Andrew! Could you add Carl's contact information to this [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1L1lbWj89wt8b2DIZhjxERJ5FCAWPDWd0nMibtc01sZk/edit#gid=0) of agencies? You may to indicate the neighborhood in the Meeting Location Column. Do you think you can email him to ask where we could have found information on the All-CAC Summit and ask to add cityscrapers@citybureau.org to their events list?

**Comment by ab1470** [comment]
@bonfirefan, the [CAC website](http://cps.edu/FACE/Pages/CAC.aspx) shows that Carl is the liaison only for the Bronzeville, Humboldt Park West, and Humboldt Park East CACs; there are four other liaisons for the remaining CACs. Do you want me to add a new spreadsheet row for each of the  liaisons? 

Alternatively, the website above lists CAC_RSVP@cps.edu as a generic contact email for the CACs, with no associated name. If we don't want to add five spreadsheet rows for each of the liaisons, we can add the generic email to the existing, single spreadsheet row.

**Comment by ab1470** [comment]
Also, I just found [this calendar](https://cpsparentu.org/apps/events2/view_calendar.jsp?id=0) (accessed from [this website](https://cpsparentu.org/)), which seems to list all of the CACs in one place. I'm not sure if anyone else has come across that calendar before, but maybe there should be a spider for it?
