### ISSUE TITLE
More tests for chi_library

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#340]
There are only [a few tests](https://github.com/City-Bureau/city-scrapers/blob/master/tests/test_chi_library.py) for the chi_library spider. We should have better coverage for this spider, something more along the lines of [this](https://github.com/City-Bureau/city-scrapers/blob/master/tests/test_chi_pubhealth.py).

**Comment by cherdeman** [comment]
Pull request #339 updated to include additional chi_library tests

**Comment by r-wei** [comment]
resolved by #339
