### ISSUE TITLE
More tests for det_schools

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/city-scrapers#341]
We'd like some more [tests](https://github.com/City-Bureau/city-scrapers/blob/master/tests/test_det_schools.py) for the det_schools spider, something along the lines of [this](https://github.com/City-Bureau/city-scrapers/blob/master/tests/test_chi_pubhealth.py).

**Comment by cherdeman** [comment]
@r-wei I'll jump in on this

**Comment by r-wei** [comment]
resolved by #350
