### ISSUE TITLE
Check Ward Night Spider

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#356]
@jim can you check on the ward night spider? I only see ~6 entries in Airtable and there should be many more. Not sure if something is off or I'm just viewing it incorrectly.

**Comment by r-wei** [comment]
@jim @pjsier This spider runs locally for me using [these instructions](https://github.com/r-wei/city-scrapers/blob/db5814ea0381aaf1701227ba394e65ae147db144/docs/faq.md), so it may be something with the deployment.

**Comment by pjsier** [comment]
@r-wei you're right, the Google API key isn't getting added to the deployment environment variables. All we should have to do is add `DOCUMENTERS_AGGREGATOR_GOOGLE_API_KEY` to the `ENV_VARS` list in `deploy/aws_setup.py`. I can add that now if that works

**Comment by r-wei** [comment]
Sounds good :)

**Comment by r-wei** [comment]
@pjsier do you want to take this opportunity to rename it `CITY_SCRAPERS_GOOGLE_API_KEY`?

**Comment by diaholliday** [comment]
It looks like this spider is putting the address in the "location_name" column when it should be in the "location_address" column. Should be an easy fix but I wanted to flag it just in case.

**Comment by r-wei** [comment]
resolved by #392
