### ISSUE TITLE
Check on CTA Spider (Chi_Transit)

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#357]
I'm not seeing board meetings for the CTA beyond May in Airtable or the basic UI but the meetings through all of 2018 are on the CTA website: https://www.transitchicago.com/board/

Can someone check on this spider to make sure it's running correctly? @bonfirefan this might have to do with the website change?

**Comment by bonfirefan** [comment]
Hey Darryl, it looks like you're seeing the schedule that they've listed on the main board page. The [Meetings, Agendas and Minutes page](https://www.transitchicago.com/board/notices-agendas-minutes/) is where they post the meeting details, and none of the meetings past May have been posted. The Spider is checking the Meeting and Agendas page. Should we scrape the main board page? It would result in some duplication when the meeting are posted to the Agendas page.

**Comment by diaholliday** [comment]
Ah ok, I understand this now. They're posting meetings some amount of time beforehand but not very far in advance. Nothing is up beyond May but the spider will pull any info as it's posted. Do we know how far in advance they're posting upcoming meetings?

And no, this one is fine, my bad. We just have to rely on them to post meetings on this page instead of using the full list they already posted but that's ok.
