### ISSUE TITLE
Update scraper names

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#358]
Listing a few spiders that need their names changed:

- [x] ~~`cps_community_action_council`: `chi_school_community_action_council`~~
- [x] `ward_night`: `chi_ward_night`
- [x] `metra_board`: `il_metra_board`
- [x] `regionaltransit`: `il_regionaltransit`(?)

**Comment by r-wei** [comment]
Also rename `ward_night` spider to `chi_ward_night`

**Comment by bonfirefan** [comment]
To add: `metra_board` to `il_metra_board`

**Comment by bonfirefan** [comment]
And `regionaltransit` to `il_regional_transit`

**Comment by r-wei** [comment]
all the names have been updated
