### ISSUE TITLE
Agency Contacts

### ISSUE THREAD

**Issue by bonfirefan** [City-Bureau/city-scrapers#362]
With priority to #256 and #232, we need to compile a list of contacts at agencies or organizations when we need to clarify event sourcing, frequency of postings, types of events, etc. All agency contacts should go to the spreadsheet: https://docs.google.com/spreadsheets/d/1L1lbWj89wt8b2DIZhjxERJ5FCAWPDWd0nMibtc01sZk/edit#gid=0

**Comment by diaholliday** [comment]
I added phone numbers for each agency to the sheet. @bonfirefan @pjsier should these numbers go into the spider or would it be easier/better to add them via the platform?

**Comment by pjsier** [comment]
I think we should only include enough information in the spiders for people to uniquely identify an agency, so phone numbers or anything else past basic info probably makes more sense in the platform

**Comment by diaholliday** [comment]
Sounds good, platform is my feeling on this one too.
