### ISSUE TITLE
New spider: Chicago Board of Ethics

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#366]
It appears the BOE only has a PDF for meetings but we may also be able to, eventually, talk to them about a better system for displaying their meetings. For now, we could definitely use a spider or some other method of pulling out all the meetings on this PDF and adding them to our system: https://www.cityofchicago.org/content/dam/city/depts/ethics/general/BoardMeetings/2018/MtgDates2018.pdf

**Comment by r-wei** [comment]
Hey @diaholliday , the spider package we're using isn't built to handle pdfs. There are other python packages and software out there that try to extract text out of pdfs, so we can leave this issue open as more of a research topic, but I think it's not a good first issue.

**Comment by diaholliday** [comment]
I or someone else can also upload them individually via the manual assignment upload form (if that puts it back in the realm of first issue): https://airtable.com/shrAUMvvmRKcOEYmu

But yes, there's a definitely research element here—namely, is there a better source for these meetings (not a PDF)

**Comment by diaholliday** [comment]
The BOE folks were kind enough to add their meetings to the org's webpage, instead of just the PDF :) This should make it significantly easier to scrape the page for meeting information. The new home for that meeting info is here: https://www.cityofchicago.org/city/en/depts/ethics/supp_info/minutes.html

**Comment by easherma** [comment]
Nice!
