### ISSUE TITLE
Chi_buildings spider revision

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#370]
This spider is working fine but it's pulling a majority of unrelated meetings. Can we revise it so that it only displays board meetings from the Public Building Commission?

**Comment by r-wei** [comment]
This spider scrapes a JSON endpoint (something like [this](http://www.pbcchicago.com/wp-admin/admin-ajax.php?action=eventorganiser-fullcal&start=20180528)), so making this change should be straightforward. I think filtering on the `className` field should do the trick.

**Comment by cherdeman** [comment]
Hi @diaholliday and @r-wei  I can grab this!

**Comment by r-wei** [comment]
Great :) I'll sign you up here: https://docs.google.com/spreadsheets/d/1wkSl3XkhEQhWYh3Dq-G8SS0uNXThqQ8CM0LJhe5i2FM/edit#gid=0  --there are some additional notes

**Comment by r-wei** [comment]
resolved by #416
