### ISSUE TITLE
New spider: Metra Citizens Advisory Board (PDF)

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#373]
Meetings can be found under the "Citizen Advisory Board Meeting" drop down at the bottom of the page: https://metrarail.com/about-metra/leadership/board-meetings

**Comment by thenoelman** [comment]
Hello!  New contributor here looking to help out.  I'd love to take this issue.

**Comment by r-wei** [comment]
hey @diaholliday and @thenoelman , we already have a [spider scraping this site](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/metra_board.py), but it can definitely be updated! Check out issue #380 for more info.
