### ISSUE TITLE
Ask HACC to add board meetings to their events feed

### ISSUE THREAD

**Issue by rebecca-burwei** [City-Bureau/city-scrapers#384]
The Housing Authority of Cook County has a [nice online calendar](http://thehacc.org/events/). This calendar is powered by two very easy to scrape "backends": [1](http://thehacc.org/wp-json/tribe/events/v1/events/), [2](http://thehacc.org/events/feed/). Unfortunately, the Housing Authority's board meetings are not listed on the calendar. Instead, they are only available in a pdf at the bottom of [this page](http://thehacc.org/about/).

We would like to ask the Housing Authority to add the board meetings to one of the easily scrapable backends.

**Comment by pjsier** [comment]
Looks like they've been added, closing
