### ISSUE TITLE
Where are the Metropolitan Water Reclamation District meetings held?

### ISSUE THREAD

**Issue by rebecca-burwei** [City-Bureau/city-scrapers#386]
The [MWRD website](http://mwrd.legistar.com/Calendar.aspx) only says "board room". We're assuming the meetings happen at MWRD headquarters, but it doesn't actually say.

**Comment by diaholliday** [comment]
Looks like it's 100 East Erie Street but we can call to confirm.

**Comment by pjsier** [comment]
Closing since we've sent Documenters and it looks like we have the location
