### ISSUE TITLE
New Spider Requests: Mayor's Advisory Councils

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#387]
Hey all, we have 2 new meetings in need of spiders—both on the same webpage:

- Mayor’s Pedestrian Advisory Council
- Mayor’s Bicycle Advisory Council

Here's the website: http://chicagocompletestreets.org/getinvolved/mayors-advisory-councils/

Good catch @ab1470!

**Comment by ab1470** [comment]
I'll take this one!

**Comment by ab1470** [comment]
As some of us in the group has already discussed, the Mayor's Bicycle Advisory Council (MBAC) and the Mayor's Pedestrian Advisory Council (MPAC) are pretty difficult to scrape. The [website](http://chicagocompletestreets.org/getinvolved/mayors-advisory-councils/) has no clear structure, and the dates have no ID or Class tags that would help us extract them. Building a spider to scrape the info would be challenging, and the spider would likely break if the website ever changes even slightly. Given all of that, here are the options that we've discussed for getting this information working:

1. Hard-code the meeting dates. The MPAC and MBAC each have only four meetings every year, and the all of the dates for the whole year are announced at the end of the preceding year. In theory, then, someone would only have to hard-code these dates once a year.
2. Subscribe to the email list. Staff will send out google calendar invites to the listed email address several months in advance, with all of the necessary information included in the body of the email. We would then need to figure out how to scrape the email. 
3. The calendar invite email described in #2 also contains a .ics attachment. I don't know how we could automate downloading and scraping the .ics file, but I could look into it if someone thinks it's promising.
4. Reach out to staff at the MPAC/MBAC and ask if they can make their Google Calendar publicly accessible (it's currently private, and only people who are subscribed to the email list will get an invitation). We would then need to figure out how to scrape the public Google Calendar.

To me, either #1 or #2 seem most promising, but of course I'm open to other suggestions. Perhaps it would be easier to discuss in person next week?
