### ISSUE TITLE
Contact Emails Needed for Agency Table

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#390]
We're getting our Best Practices document ready to send out to local departments (to help them be more efficient about publishing their public meeting info) but, in the meantime, we need to know where to send the document! 

If you have a free minute or two and want to help out: 

1) Take look at this excel sheet: https://docs.google.com/spreadsheets/d/1Uu9FmcQAy8AXhBR2bj84LbSdlfgMNNroa9P89rsDJSQ/edit#gid=0

2) Go to the "Email" column in the sheet above.

3) Use the "Link" column to copy/paste a good contact email into the sheet using the comment function. You may need to do a bit of searching depending on the link, i.e. head to the department's main website, or call the listed phone number to get the best email contact. But it'll be worth it. I'll update on next steps for the Best Practices doc soon!

**Comment by bonfirefan** [comment]
@diaholliday is this the right sheet? It looks like it's comment only. Looking to add the agency website classifications

**Comment by diaholliday** [comment]
It's set to limited access now (you should have access). I can open it up to all if we need to, or grant access as needed. This is officially the central spider doc as of last week or so.
