### ISSUE TITLE
New spiders needed

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/city-scrapers#418]
**Chicago Department of Planning and Development** (5 commissions, all appear to be on separate pages):

- [x] Chicago Zoning Board of Appeals: https://www.cityofchicago.org/city/en/depts/dcd/supp_info/zoning_board_of_appeals.html
- [x] Chicago Plan Commission: https://www.cityofchicago.org/city/en/depts/dcd/supp_info/chicago_plan_commission.html
- [x] Commission on Chicago Landmarks:
https://www.cityofchicago.org/city/en/depts/dcd/supp_info/landmarks_commission.html
- [x] Community Development Commission:
https://www.cityofchicago.org/city/en/depts/dcd/supp_info/community_developmentcommission.html
- [x] Chicago Development Fund:
https://www.cityofchicago.org/city/en/depts/dcd/supp_info/chicago_developmentfund.html

- [ ] **Chicago Housing Authority**: http://www.thecha.org/about/meetings-agendas-and-resolutions/ 

- [ ] **Chicago Board of Election Commissioners**: http://www.chicagoelections.com/en/board-meetings.html

**Mayor's Pedestrian Advisory Councils** (2 councils on separate pages):
- [ ] Mayor's Pedestrian Advisory Council:
http://chicagocompletestreets.org/getinvolved/mayors-advisory-councils/
- [ ] Mayor's Bicycle Advisory Council:
http://chicagocompletestreets.org/getinvolved/mayors-advisory-councils/

If you do claim a spider, please make a note via comment below and on the Agency Table: https://docs.google.com/spreadsheets/d/1Uu9FmcQAy8AXhBR2bj84LbSdlfgMNNroa9P89rsDJSQ/edit#gid=0

**Comment by diaholliday** [comment]
@r-wei would you mind checking to see if the Chicago Housing Authority scraper is running? I see one meeting for it on the backend but I feel like there should be more.

**Comment by diaholliday** [comment]
Just got a response from the HACC, they added the board meetings to the event calendar. They should show up now but I still need to confirm that the committees are included.

**Comment by hancush** [comment]
hey @diaholliday, i don't have write access on the table, but i left a comment – i can take on the Mayor's Bicycle Advisory Council spider.
