### ISSUE TITLE
Wayne County Commission on Health and Human Services

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#419]
New spider for Wayne County Commission on Health and Human Services (wayne_health_human_services) from 
[https://www.waynecounty.com/elected/commission/health-human-services.aspx](https://www.waynecounty.com/elected/commission/health-human-services.aspx)

This spider is currently part of ticketing group 13 on the [Public Meetings Aggregator](https://docs.google.com/spreadsheets/d/1Uu9FmcQAy8AXhBR2bj84LbSdlfgMNNroa9P89rsDJSQ/edit#gid=1214169297).

**Comment by novellac** [comment]
Needs labels:
 - location: Detroit
 - architecture: spiders
 - new spider needed

**Comment by pjsier** [comment]
Closed by #459
