### ISSUE TITLE
Wayne Commission on Economic Development

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#442]
New spider for Wayne County Commission on Economic Development (wayne_economic_development) from
https://www.waynecounty.com/elected/commission/economic-development.aspx 

This spider is currently part of ticketing group 13 on the [Public Meetings Aggregator](https://docs.google.com/spreadsheets/d/1Uu9FmcQAy8AXhBR2bj84LbSdlfgMNNroa9P89rsDJSQ/edit#gid=1214169297).

**Comment by pjsier** [comment]
Closed by #459
