### ISSUE TITLE
Wayne Commission on Government Operations

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#444]
New spider for Wayne County Commission on Government Operations (wayne_government_operations) from
https://www.waynecounty.com/elected/commission/government-operations.aspx 

This spider is currently part of ticketing group 13 on the [Public Meetings Aggregator](https://docs.google.com/spreadsheets/d/1Uu9FmcQAy8AXhBR2bj84LbSdlfgMNNroa9P89rsDJSQ/edit#gid=1214169297).

**Comment by pjsier** [comment]
Closed by #459
