### ISSUE TITLE
Suggestion: Use waffle.io as a github project manager

### ISSUE THREAD

**Issue by bdmorin** [City-Bureau/city-scrapers#460]
I use this website with a few other projects, works well.
https://waffle.io/project/create/chosen-repository?repo=City-Bureau%2Fcity-scrapers

I'm getting my feet into this project and want to start helping. I love scrapy.

**Comment by pjsier** [comment]
Thanks for the suggestion, and sorry for the delayed reply! We've mostly used GitHub Projects since they have most of the same functionality, but for this project issues alone have worked out
