### ISSUE TITLE
Wayne County Building Authority

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#466]
New spider for Wayne County Building Authority (wayne_building_authority) from
https://www.waynecounty.com/boards/buildingauthority/meetings.aspx

This spider is currently part of ticketing group 13 on the [Public Meetings Aggregator](https://docs.google.com/spreadsheets/d/1Uu9FmcQAy8AXhBR2bj84LbSdlfgMNNroa9P89rsDJSQ/edit#gid=1214169297).

**Comment by novellac** [comment]
Needs labels:

 - location: Detroit
 - architecture: spiders
 - new spider needed

**Comment by novellac** [comment]
Note that this one is labeled as a committee, but its url is under `/boards` rather than under `/elected/commission`.

**Comment by novellac** [comment]
This is referenced in pull request #463 , ready for review.

**Comment by pjsier** [comment]
Closed by #463
