### ISSUE TITLE
Detroit City Planning Commission

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#468]
New spider for Detroit City Planning Commission (det_city_planning) from
http://www.detroitmi.gov/Government/Boards/City-Planning-Commission-Information

This spider is currently part of ticketing group 1 on the [Public Meetings Aggregator](https://docs.google.com/spreadsheets/d/1Uu9FmcQAy8AXhBR2bj84LbSdlfgMNNroa9P89rsDJSQ/edit#gid=1214169297).

**Comment by novellac** [comment]
Needs labels:

 - location: Detroit
 - architecture: spiders
 - new spider needed

**Comment by pjsier** [comment]
Closed by #480
