### ISSUE TITLE
Detroit Land Bank Authority

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#471]
New spider for Detroit Land Bank Authority (det_land_bank) from
https://buildingdetroit.org/events/meetings

This spider is currently part of ticketing group 4 on the [Public Meetings Aggregator](https://docs.google.com/spreadsheets/d/1Uu9FmcQAy8AXhBR2bj84LbSdlfgMNNroa9P89rsDJSQ/edit#gid=1214169297).

**Comment by pjsier** [comment]
Closed by #473
