### ISSUE TITLE
Belle Isle Advisory Committee

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#478]
New spider for Belle Isle Advisory Committee (mi_belle_isle) from https://www.michigan.gov/dnr/0,4570,7-350-79137_79763_79901---,00.html

This spider does not have a ticketing group (it was part of Group 2 but that needs to be broken up since different/better sources have been found for some of these spiders).

**Comment by novellac** [comment]
Needs labels:

 - location: Detroit
 - architecture: spiders
 - new spider needed

**Comment by pjsier** [comment]
Closed by #488
