### ISSUE TITLE
Schedules in PDF format

### ISSUE THREAD

**Issue by jim** [City-Bureau/city-scrapers#49]
Based on a discussion, we need to document the following process for developers in the documentation:

- If a data source is difficult to scrape (data is in a PDF, image, etc.), notate that on the sources spreadsheet and don't attempt to write a scraper for it.

Tasks to close this issue:

- [ ] Add documentation on how to handle difficult to scrape sources.

-----

*Original issue content*

Not sure if we want to get into trying to parse PDFs, but the [Chicago Housing Authority's meetings](http://www.thecha.org/about/board-of-commissioners/board-information-and-meetings/) are posted as an image and PDF.

Is it worth trying to automate the import of this information? Or is is better to just have a list of sources that a human needs to enter into the system once per year?

**Comment by jim** [comment]
Looks like the Illinois Department of Corrections Advisory Board also posts most of their info inside PDFs. Here's the notice for their next meeting: https://www.illinois.gov/idoc/aboutus/advisoryboard/Pages/default.aspx

**Comment by jim** [comment]
The [Cook County Commission on Human Rights](https://www.cookcountyil.gov/agency/commission-human-rights-0) also uses PDFs.

**Comment by jim** [comment]
Same with [Housing Authority of Cook County](http://thehacc.org/about/): http://thehacc.org/wp-content/uploads/2017/08/2017-Scheduled-Board-Meetings.pdf

**Comment by eads** [comment]
cc @diaholliday

**Comment by diaholliday** [comment]
@jim we talked about this a moment ago but I wanted to post here as well in case anyone has the same question:

The Documenters program will eventually employ a Documenters Manager that will coordinate and assign meetings to Documenters—the manager will also be tasked with manually inputting meeting ties and locations that can't be scraped.

If you come across a PDF or other means of listing events that can't be scraped please note that and the form of documentation (PDF, etc) on the public meeting excel sheet. I'll eventually go through the list and create a list for the Documenters Manager to check on a recurring basis and add manually to the calendar.

**Comment by jim** [comment]
@diaholliday Cool. I think the TODO here is to add that to the project docs, and I'll close this ticket when that has been done.

**Comment by r-wei** [comment]
I added a column in the spreadsheet for this
