### ISSUE TITLE
Detroit Board of Zoning Appeals

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#494]
New spider for Detroit Board of Zoning Appeals (det_zoning_appeals) from https://www.detroitmi.gov/Government/Boards/Board-of-Zoning-Appeals-Meeting

This spider does not have a ticketing group (it was part of Group 2 but that needs to be broken up since different/better sources have been found for some of these spiders).

**Comment by novellac** [comment]
Needs labels:

 - location: Detroit
 - architecture: spiders
 - new spider needed

**Comment by pjsier** [comment]
Closed by #495
