### ISSUE TITLE
Wayne County Election Commission 

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#500]
New spider for Wayne County Election Commission (wayne_election_commission) from https://www.waynecounty.com/elected/clerk/election-commission.aspx

This spider is is new and does not have a ticketing group. I will try to use the wayne_mixin, in which case it would be part of ticket group 13. If that's not possible, it should be considered its own group.

**Comment by novellac** [comment]
Needs labels:

 - location: Detroit
 - architecture: spiders
 - new spider needed

**Comment by novellac** [comment]
Was not able to use the wayne mixin, and should be considered its own ticketing group.

**Comment by pjsier** [comment]
Closed by #502
