### ISSUE TITLE
Detroit City Council

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#503]
New spider for Detroit City Council (det_city_council) from 
http://www.detroitmi.gov/Government/City-Council/City-Council-Sessions

These spiders need to be assigned their own ticketing group. They currently take up rows 21-28 on the spiders spreadsheet: https://docs.google.com/spreadsheets/d/1Uu9FmcQAy8AXhBR2bj84LbSdlfgMNNroa9P89rsDJSQ/edit#gid=1214169297

**Comment by novellac** [comment]
Needs labels:

 - location: Detroit
 - architecture: spiders
 - new spider needed

**Comment by pjsier** [comment]
Closed by #508
