### ISSUE TITLE
are there any events that could be collected from email lists

### ISSUE THREAD

**Issue by eads** [City-Bureau/city-scrapers#52]
Suggested by @milti

**Comment by bonfirefan** [comment]
According to #337, it seems like the Humboldt Park east Community Action Council events are email-only. It's highly likely that other CAC events are email-based as well. For email-only events, let's ask them to add cityscrapers@citybureau.org (I'll let @diaholliday verify)

**Comment by diaholliday** [comment]
Yes, that's the best address, thanks for connecting these issues!

**Comment by pjsier** [comment]
We have an updated setup for this where emails received at notice@documenters.org are forwarded to S3 where we can scrape them here https://github.com/City-Bureau/store-inbound-emails
