### ISSUE TITLE
Pittsburgh City Council Spider

### ISSUE THREAD

**Issue by bonfirefan** [City-Bureau/city-scrapers#528]
@RonakDedhia @ishabandi67 are working on Pittsburgh City Council http://pittsburghpa.gov/clerk/council-meetings which uses Legistar: https://pittsburgh.legistar.com/Calendar.aspx
Spider Name: pitt_city_council

The [cook_board](https://github.com/City-Bureau/city-scrapers/blob/8b3e7204cf2207b2a408e65c2179472492878004/city_scrapers/spiders/cook_board.py) spider uses Legistar.

**Comment by bonfirefan** [comment]
This covers the following: 
<li class="rcbItem">City Council</li><li class="rcbItem">Committee on Finance and Law </li><li class="rcbItem">Committee on Hearings </li><li class="rcbItem">Committee on Human Resources </li><li class="rcbItem">Committee on Intergovernmental Affairs</li><li class="rcbItem">Committee on Land Use and Economic Development</li><li class="rcbItem">Committee on Public Safety Services</li><li class="rcbItem">Committee on Public Works </li><li class="rcbItem">Committee on Urban Recreation </li>

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/3
