### ISSUE TITLE
Readme contains some broken links

### ISSUE THREAD

**Issue by novellac** [City-Bureau/city-scrapers#530]
File: README.md
Section: "Ready to code with us?" 
Subsection: "3. Get started with Installation and Contributing a spider." 
Issue: The "Installation" and "Contributing a spider" links are no longer valid.
Side note: Is there somewhere else we can find the old docs? They were really helpful for me when I was on-boarding!

**Comment by pjsier** [comment]
@novellac thanks for flagging this! I'll make the update. In the meantime, all the previous docs are here https://cityscrapers.org/docs/development/

**Comment by pjsier** [comment]
Fixed in 5570423b247c73ec3d082828b967f74f65bc0caf
