### ISSUE TITLE
Rewrite Detroit City Planning Commission scraper

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#537]
The city of Detroit recently updated its website, so we'll need to rewrite this scraper. We may be able to generalize the scraper behavior similarly to the [Wayne Commission mixin](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/mixins/wayne_commission.py)

**Comment by novellac** [comment]
Looks like the old page is down and the new page is [https://www.detroitmi.gov/government/commissions/city-planning-commission/city-planning-commission-meetings] 
There are no meetings up yet, but since it looks like they changed CMS maybe they're still in the midst of a data migration. :)
