### ISSUE TITLE
Rewrite Detroit Police Commissioners scraper

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#538]
The city of Detroit recently updated its website, so we'll need to rewrite this scraper. We may be able to generalize the scraper behavior similarly to the [Wayne Commission mixin](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/mixins/wayne_commission.py)

**Comment by novellac** [comment]
According to the new site [https://www.detroitmi.gov/government/boards/board-police-commissioners] the meetings are routine, and the listed dates are actually for recess. How should we handle this kind of case?

**Comment by pjsier** [comment]
This one might be worth holding off on to see if more info is migrated too. We have a scraper that handles the once a week case for Chicago Aldermanic ward nights, but I'd be more hesitant to do that here

**Comment by pjsier** [comment]
Closed by #688
