### ISSUE TITLE
Rewrite Detroit Zoning Board of Appeals scraper

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#539]
The city of Detroit recently updated its website, so we'll need to rewrite this scraper. We may be able to generalize the scraper behavior similarly to the [Wayne Commission mixin](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/mixins/wayne_commission.py)

**Comment by novellac** [comment]
Interesting! I'll have a look at it if no one else has already grabbed this one.

**Comment by pjsier** [comment]
@novellac it's all yours! It looks like this just happened in the past few days, so feel free to reach out if anything interesting comes up. We haven't looked much at the new site at all
