### ISSUE TITLE
Spider: City of Pittsburgh Planning Commission

### ISSUE THREAD

**Issue by bonfirefan** [City-Bureau/city-scrapers#543]
@dkori @nathanderon Are working on this

City of Pittsburgh Planning Commission
Hearing Notices / Planning Commission http://pittsburghpa.gov/dcp/notices

This is a plain text with event names as ‘p tags’ and details as ‘ul’ //an unordered list
Spider Name: pitt_city_planning
Issue: https://github.com/City-Bureau/city-scrapers/issues/543

**Comment by nathanderon** [comment]
Correction: @nathanderon, not @nderon

**Comment by bonfirefan** [comment]
According to the [Pittsburgh Planning Commission](http://apps.pittsburghpa.gov/dcp/Planning_Commission.pdf), meetings: 

> City   Planning   Commission   meetings   are   held   every   
> other Tuesday beginning in the early afternoon. They are 
> located downtown on the 1st floor of the Civic Building at 
> 200 Ross Street.   
> Planning  Commission  agendas,  applicant  presentations,  
> and minutes are posted online at pittsburghpa.gov/dcp/  
> From  the  City  Planning  home  page,  click  on  “Planning  
> Commission”  on  the  right  hand  menu.  To  receive  the  
> agenda   by   email,   please   contact   Dolores   Hanna   at         
> dolores.hanna@pittsburghpa.gov or 412-255-2473.
> Briefing
> At  approximately    1  PM,  the  Commission  hears  project  
> briefings off of the official record.  The public is welcome to 
> observe, but no public comments are taken.  The briefing 
> portion of the meeting provides an initial presentation to 
> the Commission, then projects return in two weeks on the 
> Hearing and Action agenda.  
> Hearing and Action
> Hearing   and   Action   begins   no   earlier   than   2   PM.      
> Applicants   make   a   presentation   again,   including   any   
> revisions   or   additional   information   requested   by   the   
> Commission  during  briefing.    Public  comment  is  then  
> accepted—limited  to  3  minutes  per  person,  per  project.    
> The  Commission  usually  votes  on  projects  the  same  day  
> they are presented for Hearing and Action.

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/4
