### ISSUE TITLE
Spider: Urban Redevelopment Authority of Pittsburgh

### ISSUE THREAD

**Issue by bonfirefan** [City-Bureau/city-scrapers#547]
Urban Redevelopment Authority of Pittsburgh:
Meetings of the URA Board of Directors are held on the second Thursday of each month at 2 p.m. in the Wherrett Room on the 13th floor at 200 Ross Street, Pittsburgh, PA 15219. https://www.ura.org/pages/board-meeting-notices-agendas-and-minutes
Spider Name: pitt_urbandev

@maitrivasa15 is working on this!

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/5
