### ISSUE TITLE
Spider: Chicago Special Service Area #16 Greektown

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#558]
URL: https://www.wcachicago.org/ssa-16
Spider Name: `chi_ssa_16`
Agency Name: Chicago Special Service Area #16 Greektown

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by pg** [comment]
The site has a member access password...

**Comment by pjsier** [comment]
Weird, this site has changed a lot and looks like it's still being updated

**Comment by benjaminfawcett** [comment]
https://greektownchicago.org/about/ssa-16/ Found this site that seems to be reporting information of interest. Interested in working on this issue.

**Comment by pjsier** [comment]
Closed by #947, thanks @benjaminfawcett!
