### ISSUE TITLE
Spider: Chicago Special Service Area #18 North Halsted

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#559]
URL: https://northalsted.com/community/
Spider Name: `chi_ssa_18`
Agency Name: Chicago Special Service Area #18 North Halsted

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by AmiMappy** [comment]
Can I work on this?

**Comment by pjsier** [comment]
@AmiMappy all yours!

**Comment by AmiMappy** [comment]
I keep getting the 'no module named city_scrapers_core' error. Help needed.

**Comment by AmiMappy** [comment]
I keep getting the 'no module named legistar' error. Help needed.

**Comment by AmiMappy** [comment]
What classification should I provide the spider with?
(ADVISORY_COMMITTEE, BOARD, CITY_COUNCIL, COMMISSION, COMMITTEE, FORUM, POLICE_BEAT, NOT_CLASSIFIED). By default, it is NOT_CLASSIFIED.

**Comment by pjsier** [comment]
The SSAs are generally commissions, so `COMMISSION` would be best

**Comment by AmiMappy** [comment]
Thanks.

**Comment by AmiMappy** [comment]
What should I put in _parse_links()?

**Comment by pjsier** [comment]
You can take a look at some of the other scrapers [for examples](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/chi_ssa_26.py#L50-L69), but in general you want to find agendas and minutes and return a list of dictionaries with `title` and `href` keys. Also feel free to [join the Slack](https://airtable.com/shrsdRcYVzp019U22) for general questions

**Comment by AmiMappy** [comment]
Can you help me on how I should go about this? :

          ERROR: /home/travis/build/City-Bureau/city-scrapers/chi_ssa_18.py Imports are incorrectly sorted.

          ---/home/travis/build/City-Bureau/city-scrapers/chi_ssa_18.py:before	2019-10-05 12:20:37.663324

         +++ /home/travis/build/City-Bureau/city-scrapers/chi_ssa_18.py:after	2019-10-05 12:21:23.801026

         @@ -1,6 +1,5 @@

         +import re
          from datetime import datetime, time
         -import re
          from city_scrapers_core.constants import COMMISSION
          from city_scrapers_core.items import Meeting

**Comment by pjsier** [comment]
@AmiMappy It looks like you still need to run the style checks, more info here https://cityscrapers.org/docs/development/#6-run-linting-and-style-checking-tools

**Comment by AmiMappy** [comment]
I run the tests, but I get an error. 
[Error.txt](https://github.com/City-Bureau/city-scrapers/files/3693983/Error.txt)
I don't get it entirely. Help needed.

**Comment by pjsier** [comment]
@AmiMappy I saw a few pull requests for this get created and closed. I'm happy to answer any questions about the setup and how to submit a PR, but the Slack might be easier if that works for you. In the meantime the [development docs](https://cityscrapers.org/docs/development/) and [contributing guidelines](https://github.com/City-Bureau/city-scrapers/blob/master/CONTRIBUTING.md) should have some more info

**Comment by luchiago** [comment]
Is this issue still need help?

**Comment by nick-symon** [comment]
Hi there! I'd like to claim this if its still available

**Comment by pjsier** [comment]
@nick-symon sounds good! Assigning you now

**Comment by pjsier** [comment]
Closed by #945, thanks @nick-symon!
