### ISSUE TITLE
Spider: Chicago Special Service Area #21 Lincoln Square Ravenswood

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#560]
URL: http://www.lincolnsquare.org/SSA-no-21-Commission-meetings
Spider Name: `chi_ssa_21`
Agency Name: Chicago Special Service Area #21 Lincoln Square Ravenswood

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by MrDiggles2** [comment]
@pjsier - Hi! I'm interested in taking up this work.

**Comment by pjsier** [comment]
@MrDiggles2 great! Feel free to reach out with any questions here or on our Slack (you can join by filling out [this form](https://airtable.com/shrsdRcYVzp019U22) if you aren't in it now)
