### ISSUE TITLE
Spider: Chicago Special Service Area #22 Clark St/Andersonville

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#561]
URL: http://www.andersonville.org/our-organizations/andersonville-ssa-22/
Spider Name: `chi_ssa_22`
Agency Name: Chicago Special Service Area #22 Clark St/Andersonville

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by annaderengowski** [comment]
I'd like to take a crack at this issue, if that's okay!

**Comment by pjsier** [comment]
@annaderengowski sounds good!

**Comment by zuzaman** [comment]
I would like a claim on this please.

**Comment by pjsier** [comment]
@zuzaman I'll mark it claimed now

**Comment by pjsier** [comment]
Closed by #953, thanks @zuzaman!
