### ISSUE TITLE
Spider: Chicago Special Service Area #23 Clark St/Lincoln Park

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#562]
URL: visitclarkstreet.com/clark-street-ssa-commission-meetings-pages-182.php
Spider Name: `chi_ssa_23`
Agency Name: Chicago Special Service Area #23 Clark St/Lincoln Park

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by mericleac** [comment]
Hi! I'd like to try this for my first contribution.

**Comment by pjsier** [comment]
@mericleac sounds good!

**Comment by mericleac** [comment]
Visiting visitclarkstreet.com redirects to lincolnparkchamber.com. The new URL for this special service area's meetings seems to be https://www.lincolnparkchamber.com/clark-street-ssa-administration/.

**Comment by zuzaman** [comment]
@pjsier! Hello! I would like to give this issue a go. I can see that the previous contributor already found the live link where the next meeting schedules are shared.

**Comment by zuzaman** [comment]
So I played around a bit, as web scraping is a completely new thing for me, and now I have a mock version that that creates the meeting entries for the current year. 

As this is my first commit I would like to ask two questions:
1. Are the dates between 2016-2019 also interesting for the scraper? Or only the ones of the current year?
2. Pre-2020 meetings have in this case agendas and meeting minutes available in separate files. I am not sure if documents of the current year are also uploaded or that is only done later. Should both of them get attached as a link to the meeting entry?

**Comment by pjsier** [comment]
@zuzaman sounds great! For the first question, they're interesting if they follow the same format, but we don't always want to slow down the spider by pulling them every day. We've been using a `CITY_SCRAPERS_ARCHIVE` setting to control pulling older meetings where it's easy, but if it introduces complications feel free to ignore them https://github.com/City-Bureau/city-scrapers/blob/c835f0cedd36683c2ea64e28e7c8359badfd3009/city_scrapers/spiders/chi_zoning_board.py#L33

For the second point, we do want those links, but if they aren't included now you can implement some basic checks off of how they look in the past. More info in the docs https://cityscrapers.org/docs/development/#links

**Comment by zuzaman** [comment]
Ok thanks for the hints. I opened a pull request.

**Comment by pjsier** [comment]
Closed by #949, thanks @zuzaman!
