### ISSUE TITLE
Spider: Chicago Special Service Area #27 Lakeview West

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#565]
URL: https://www.lakeviewchamber.com/ssa27
Spider Name: `chi_ssa_27`
Agency Name: Chicago Special Service Area #27 Lakeview West

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by nmschorr** [comment]
I'm working on this one. It's actually somewhat done; just getting ready to submit and checking the instructions on how. Haven't written the Pytests yet but I know how and will soon.

**Comment by pjsier** [comment]
Great, thanks for the update @nmschorr!

**Comment by nmschorr** [comment]
I've had some trouble with naming things. And I think one of your commit messages migrated onto my work. I'll try to fix what I can.

**Comment by nmschorr** [comment]
If anyone is interested in working on this one - I've made some progress. Please see https://github.com/nmschorr/city-scrapers/tree/0565-spider-chi_ssa_27 as my code hasn't been accepted yet and isn't in the master tree yet.

**Comment by pjsier** [comment]
Closed by #785 thanks!
