### ISSUE TITLE
Spider: Chicago Special Service Area #48 Old Town

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#569]
URL: https://oldtownchicago.org/ssa-48/
Spider Name: `chi_ssa_48`
Agency Name: Chicago Special Service Area #48 Old Town

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by danielahuang** [comment]
Hi I'm interested in working on this spider

**Comment by pjsier** [comment]
It’s all yours, feel free to reach out with questions here or on slack!

**Comment by WhatAreYouSaying** [comment]
Can I have a try on this spider?

**Comment by Mc33k** [comment]
Hi, I would like to take a look at this issue.

**Comment by pjsier** [comment]
@Mc33k all yours!

**Comment by Mc33k** [comment]
Hi, I just wanted to let you know, that I was not able to make a lot of progress due to lack of free time. However that should not be a problem during Christmas and I still want to continue to work on this issue.

**Comment by pjsier** [comment]
Closed by #942, thanks @Mc33k!
