### ISSUE TITLE
Spider: Chicago Special Service Area #73 Chinatown

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#570]
URL: https://chinatownssa73.org/meeting-schedule/
Spider Name: `chi_ssa_73`
Agency Name: Chicago Special Service Area #73 Chinatown

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by grovesjo** [comment]
I'm interested in building this spider.

**Comment by pjsier** [comment]
@grovesjo all yours!

**Comment by pjsier** [comment]
Closed by #757, thanks @grovesjo!
