### ISSUE TITLE
Spider: Chicago Special Service Area #2 Belmont/Central

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#571]
URL: http://belmontcentral.org/about-ssa-2/ssa2-meeting-minutes-audit/
Spider Name: `chi_ssa_2`
Agency Name: Chicago Special Service Area #2 Belmont/Central

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by yu-zhou-7** [comment]
I would like to try this one if that's ok! Although it appears that the website hasn't been updated in quite a while. Should we still try to scrape it or try to find out if the meeting reminders/minutes were moved somewhere else?

**Comment by pjsier** [comment]
@yu-zhou-7 up to you! A lot of the SSAs aren't updating their meetings online, even though they're typically required to, so in many cases we're just archiving what's there and watching it in case they do update it. You're welcome to try a different one, but we're still interested in this

**Comment by yu-zhou-7** [comment]
Gotcha.

Question about an issue I'm seeing. I'm seeing a bunch of these errors popup on existing tests:
![image](https://user-images.githubusercontent.com/15326553/61543974-74f72d00-aa12-11e9-987c-32fb052a3c30.png)
It's something that's easily fixed if I just add "encoding='utf-8'" to the last line in utils.py. Am I doing something wrong in the setup or should this be updated?

**Comment by pjsier** [comment]
@yu-zhou-7 thanks for catching that! I thought we had caught it, but I guess not. Do you want to put in a separate PR for that fix to `utils.py` just to keep things clean?

**Comment by yu-zhou-7** [comment]
Sure thing!

**Comment by pjsier** [comment]
Closed by #793, thanks @yu-zhou-7!
