### ISSUE TITLE
Spider: Chicago Special Service Area #51 Chatham

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#573]
URL: http://www.cbatechworks.org/
Spider Name: `chi_ssa_51`
Agency Name: Chicago Special Service Area #51 Chatham

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by yu-zhou-7** [comment]
I can work on this one

**Comment by pjsier** [comment]
Sounds good!

**Comment by pjsier** [comment]
Closed by #794, thanks @yu-zhou-7!
