### ISSUE TITLE
Spider: Chicago Special Service Area #52 51st Street

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#574]
URL: https://www.51ststreetchicago.com/about.html
Spider Name: `chi_ssa_52`
Agency Name: Chicago Special Service Area #52 51st Street

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by lilianhj** [comment]
I'm working on this!

**Comment by jusadi** [comment]
It looks like the old URL is 404-ed. Looks like a possible replacement is: [https://www.51ststreetchicago.com/about.html](https://www.51ststreetchicago.com/about.html).

**Comment by pjsier** [comment]
@jusadi that looks right! Are you interested in working on this one?

**Comment by jusadi** [comment]
Yeah! I'd work on it.

**Comment by jusadi** [comment]
The page does not seem updated for 2020.

**Comment by pjsier** [comment]
It looks like they didn't update the header but the dates are updated now @jusadi

**Comment by sosolidkk** [comment]
If no one is working on this, i'd like to take it.

**Comment by pjsier** [comment]
@sosolidkk all yours! Assigning you now

**Comment by sosolidkk** [comment]
I'm sorry for the delay. I've run into some heavy workload at job, but I'll submit a PR soon. Just posting this comment to say that I'm still working on it

**Comment by pjsier** [comment]
Closed by #983, thanks @sosolidkk!
