### ISSUE TITLE
Spider: Chicago Special Service Area #60 Albany Park

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#575]
URL: https://northrivercommission.org/events/
Spider Name: `chi_ssa_60`
Agency Name: Chicago Special Service Area #60 Albany Park

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by bendiller** [comment]
Hi Patrick - this one's looking dormant, can I take it?

**Comment by pjsier** [comment]
Sounds good!

**Comment by bendiller** [comment]
Great! Would you mind taking a minute and going through a couple months on https://northrivercommission.org/events/ and listing out which you'd like the spider to process and which to ignore? I did a poor job of guessing on the last spider and wasted a bunch of time because of that.

Thanks!

**Comment by pjsier** [comment]
I think it's safest to only include events with "Meeting", "Committee" or "Advisory Council" in the name or description. We can ignore the workshops and social events

**Comment by bendiller** [comment]
Great, thanks!

**Comment by pjsier** [comment]
Closed by #900
