### ISSUE TITLE
Spider: Housing Authority of the City of Pittsburgh

### ISSUE THREAD

**Issue by bonfirefan** [City-Bureau/city-scrapers#576]
Housing Authority of the City of Pittsburgh
hacp.org, http://www.hacp.org/public-information/board-info
Spider name: pitt_housing

This is particularly relevant given the [housing summit this weekend in Pittsburgh.](housingsummitpgh.org)

**Comment by pjsier** [comment]
Closed by #579

**Comment by bonfirefan** [comment]
It looks like they have changed their URL to http://www.hacp.org/public-information/board-info
The http://www.hacp.org/public-information/board-info URL now throws a 404 error. Does someone want to modify the existing pitt_housing spider that @dpimpinella created? @dpimpinella you get first dibs, of course.

**Comment by dpimpinella** [comment]
@bonfirefan I'll take care of this one!

**Comment by dpimpinella** [comment]
@bonfirefan I won't be able to complete this within a reasonable time frame, so i'm putting it back up for grabs.

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/7
