### ISSUE TITLE
Spider: Allegheny County Council

### ISSUE THREAD

**Issue by bonfirefan** [City-Bureau/city-scrapers#578]
Allegheny County: This spider uses Legistar, meaning we will use the Legistar API. Please template it using the [cook_board spider](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/cook_board.py). 

spider name: alle_city
https://alleghenycounty.legistar.com/Calendar.aspx

Covers the following:

<ul class="rcbList" style="list-style:none;margin:0;padding:0;zoom:1;"><li class="rcbItem">Committee on Appointment Review</li><li class="rcbItem">Committee on Budget and Finance</li><li class="rcbItem">Committee on Economic Development &amp; Housing</li><li class="rcbItem">Committee on Government Reform</li><li class="rcbItem">Committee on Health &amp; Human Services</li><li class="rcbItem">Committee on Human Services</li><li class="rcbItem">Committee on Parks</li><li class="rcbItem">Committee on Public Safety</li><li class="rcbItem">Committee on Public Works</li><li class="rcbItem">County Council</li><li class="rcbItem">County Council - Special Meeting</li><li class="rcbItem">Executive Committee</li><li class="rcbItem">Public Hearing</li><li class="rcbItem">Special Committee on Education</li><li class="rcbItem">Special Committee on Elections</li><li class="rcbItem">Special Committee on Government Reform</li><li class="rcbItem">Special Committee on Insurance</li><li class="rcbItem">Special Committee on Marketing</li><li class="rcbItem">Special Committee on Parks and Public Works</li><li class="rcbItem">Special Committee on Property Assessments</li><li class="rcbItem">Special Committee on Reapportionment</li><li class="rcbItem">Special Committee on the Councils of Governments</li><li class="rcbItem inactiveComboItem" style="color:Gray;">Committee on Campaign Finance Reform (inactive)</li></ul>

**Comment by bonfirefan** [comment]
@thoo is working on this

**Comment by dpimpinella** [comment]
Just to avoid any confusion, @thoo and @bonfirefan, I mistakenly referenced this issue in my PR for another issue, so please ignore that. I have not done any work on this specific issue. Thanks!

**Comment by thoo** [comment]
@dpimpinella np. It happens all the time. :)

**Comment by thoo** [comment]
I don't see csv file at `local_outputs`. I can see all the parsed text in CLI.

**Comment by pjsier** [comment]
@thoo right now the local output pipeline is commented out here: https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/settings/base.py#L30

You can try re-enabling it, but I think it may not be working as of now due to some of our schema updates

**Comment by thoo** [comment]
@pjsier Thanks. It is still working.

**Comment by pjsier** [comment]
@thoo thanks for catching that! It sounds like we just need to update the version of `twisted`? Feel free to open an issue for that. If it is just a version issue the best way to address it would be to use `pipenv` to update the `Pipfile` to allow for Python 3.5-3.7, specify `twisted` as its own dependency, and then update the `requirements.txt` from `pipenv lock -r`

**Comment by thoo** [comment]
@pjsier Sure. I will open PR.

**Comment by thoo** [comment]
@pjsier Sure go ahead. I haven't started yet. For python 3.7, I have to install `twisted` from `pip install git+https://github.com/twisted/twisted `. As you know, python3.7 introduces `asyncio` and `async/await` is used and `twisted` has a variable name (`async`). The github master for `twisted` is already updated even though it is not released yet.
