### ISSUE TITLE
Spider: Pittsburgh Zoning Board of Adjustment

### ISSUE THREAD

**Issue by dpimpinella** [City-Bureau/city-scrapers#586]
Pittsburgh's Zoning Board of Adjustment

URL: http://pittsburghpa.gov/dcp/zba-schedule
Spider name: pitt_zoning
Agency name: Zoning Board of Adjustment

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/8
