### ISSUE TITLE
Spider: Pittsburgh Department of Mobility and Infrastructure

### ISSUE THREAD

**Issue by dpimpinella** [City-Bureau/city-scrapers#587]
Pittsburgh Department of Mobility and Infrastructure

URL: http://pittsburghpa.gov/domi/index.html
Spider name: pitt_mobility_infra
Agency Name: Pittsburgh Department of Mobility and Infrastructure

**Comment by wingroove** [comment]
I am interested in taking this on!

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/9
