### ISSUE TITLE
Spider: Housing Opportunity Fund Advisory Board Pittsburgh

### ISSUE THREAD

**Issue by jasonbaik94** [City-Bureau/city-scrapers#589]
https://www.ura.org/events/housing-opportunity-fund-advisory-board-meeting
Spider: pitt_housing_opp

**Comment by jasonbaik94** [comment]
I'm working this

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/11
