### ISSUE TITLE
Spider: Allegheny County Sanitary Authority (ALCOSAN)

### ISSUE THREAD

**Issue by dpimpinella** [City-Bureau/city-scrapers#592]
URL: http://www.alcosan.org/BoardofDirectors/2015MeetingSchedule/tabid/195/Default.aspx
Spider name: alle_sanitary
Agency name: Allegheny County Sanitary Authority

**Comment by ben-nathanson** [comment]
I'm working on this!

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/14
