### ISSUE TITLE
Spider: The Pittsburgh Water and Sewer Authority Board

### ISSUE THREAD

**Issue by dpimpinella** [City-Bureau/city-scrapers#593]
URL: http://www.pgh2o.com/board
Spider name: pitt_water
Agency name: The Pittsburgh Water and Sewer Authority Board

**Comment by ben-nathanson** [comment]
I'm working on this issue

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/15
