### ISSUE TITLE
Spider: Allegheny County Finance and Development Commission

### ISSUE THREAD

**Issue by dpimpinella** [City-Bureau/city-scrapers#597]
URL: http://www.county.allegheny.pa.us/economic-development/authorities/meetings-reports/fdc/meetings.aspx
Spider name: alle_finance_dev
Agency name: Allegheny County Finance and Development Commission

Currently, the Finance and Development Commission (FDC) meetings include the meetings for all of the following organizations:
 
Higher Education Building Authority (HEBA)
Hospital Development Authority (HDA)
Industrial Development Authority (IDA)
Residential Finance Authority (RFA)

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/18
