### ISSUE TITLE
Spider: Allegheny County Authority for Improvements in Municipalities

### ISSUE THREAD

**Issue by dpimpinella** [City-Bureau/city-scrapers#598]
URL: http://www.county.allegheny.pa.us/economic-development/authorities/meetings-reports/aim/meetings.aspx
Spider name: alle_improvements
Agency name: Authority for Improvements in Municipalities

**Comment by bruceadams** [comment]
I recommend using the HTTPS site: https://alleghenycounty.us/economic-development/authorities/meetings-reports/aim/meetings.aspx

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/19
