### ISSUE TITLE
Spider: Partner4Work Board of Directors

### ISSUE THREAD

**Issue by dpimpinella** [City-Bureau/city-scrapers#599]
URL: https://www.partner4work.org/about/board-meetings
Spider name: pitt _partner4work
Agency name: Partner4Work

**Comment by bonfirefan** [comment]
It looks like the most recently posted meeting was in 2017. Bruce has an email out asking for clarification on their meetings.

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/20
