### ISSUE TITLE
Spider: Redevelopment Authority of Allegheny County 

### ISSUE THREAD

**Issue by dpimpinella** [City-Bureau/city-scrapers#601]
URL: https://www.alleghenycounty.us/economic-development/authorities/meetings-reports/raac/meetings.aspx
Spider name: alle_redevelopment_authority
Agency name: Redevelopment Authority of Allegheny County

**Comment by jondyer** [comment]
I'm on it!

**Comment by guesschess** [comment]
I will work on this.

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/21
