### ISSUE TITLE
Spider: Board of Property Assessments and Appeals Review

### ISSUE THREAD

**Issue by dpimpinella** [City-Bureau/city-scrapers#602]
URL: http://www.county.allegheny.pa.us/real-estate/assessment-appeals/bpaar.aspx
Spider name: alle_property_assessment
Agency name: Allegheny County Board of Property Assessments and Appeals Review

**Comment by pjsier** [comment]
Moved to https://github.com/bonfirefan/city-scrapers-pitt/issues/22
