### ISSUE TITLE
Spider: Allegheny County Council

### ISSUE THREAD

**Issue by dpimpinella** [City-Bureau/city-scrapers#603]
URL: https://www.alleghenycounty.us/county-council/council-meetings.aspx
Spider name: alle_county_council
Agency name: Allegheny County Council

**Comment by pwprosap** [comment]
I will look to take on this Spider and work on it over the holiday break. I will also look for potential other sites that might house this info.

**Comment by pwprosap** [comment]
After speaking with Bonnie we found a good Legistar website for this spider. I will be using the following URL for this spider instead of the one in the original post:
URL: [https://alleghenycounty.legistar.com/Calendar.aspx](https://alleghenycounty.legistar.com/Calendar.aspx)

**Comment by bonfirefan** [comment]
@pwprosap bad news, it looks like this was already closed in #580 by @thoo! It looks like it got re-added in our round 2 of issue opening. I suggest you work on #597 or another open issue.
