### ISSUE TITLE
Chicago Board of Election Commissioners

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#604]
URL: https://chicagoelections.com/en/board-meetings.html
Spider name: `chi_board_elections`
Agency name: Chicago Board of Election Commissioners

The current month's meeting can be pulled from the page, the past times aren't regular, but we might be able to pull minutes/video from the archive page https://chicagoelections.com/en/meeting-minutes-and-videos.html

**Comment by pjsier** [comment]
@zarifmahmud yep, it's all yours! Feel free to reach out with any questions

**Comment by zarifmahmud** [comment]
Could you add me to to Slack? I have some questions about the City Scrapers specifications.

**Comment by pjsier** [comment]
Closed by #608
