### ISSUE TITLE
Spider: Chicago Housing Authority

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#624]
URL: http://www.thecha.org/about/board-meetings-agendas-and-resolutions
Spider Name: `chi_housing_authority`
Agency Name: Chicago Housing Authority
Meeting Name: Board of Commissioners

See the contribution guide for information on how to get started

**Comment by jackycute** [comment]
I'm working on this one.

https://www.thecha.org/about/board-meetings-agendas-and-resolutions/board-information-and-meetings

**Comment by pjsier** [comment]
Thanks for the interest @jackycute! I actually assigned this one to myself already because there are some quirks that we’ve been working through, but let me know if you’re looking for other Chicago scrapers

**Comment by jackycute** [comment]
Nice to meet you guys tonight!
Let me know if there's anything I can help.
Also, people can try to use https://hackmd.io for documentation.
