### ISSUE TITLE
Spider: Iowa City City Council

### ISSUE THREAD

**Issue by agurtovoy** [City-Bureau/city-scrapers#654]
I started working on the [Iowa City City Council](https://www.icgov.org/city-government/departments-and-divisions/city-council) meetings scrapper, and thought I'd create an issue to document this. 

(Also, I need an issue number to follow the recommended branch name pattern :)

**Comment by pjsier** [comment]
We have an updated setup for creating a City Scrapers project for your area in https://github.com/City-Bureau/city-scrapers-template, so I'm closing this. Happy to answer any questions about the setup though!
