### ISSUE TITLE
Pull Board of Ethics in cook_county scraper

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#656]
Most of the events in the calendar used in the `cook_county` scraper are duplicated from `cook_board`, so we're applying a filter for only the events classified as forums. This is leaving out Board of Ethics events, so we'll need to find out a way of including these, but ignoring everything else that isn't a forum

**Comment by pyence** [comment]
Hey, I'm pretty new to scrapy but I'm working on this.  
Would a separate spider be acceptable? or two separate initial requests?

**Comment by pjsier** [comment]
@pyence sounds great! I think a separate scraper would actually be ideal here, let me know if you have any questions

**Comment by pjsier** [comment]
Closed by #876, thanks @pyence!

**Comment by pyence** [comment]
Sure thing! Happy to help :smile: 

I'd also like to implement the freezegun boilerplate in tests/test_cook_county.py. Should I open an issue for this?

**Comment by pjsier** [comment]
That sounds great. You can create a new issue for that and just mention you're working on it. If you're updating that file, it would also be good to replace the `file_response` function with the one from `city_scrapers_core` and there should be a good amount of examples of that in the other tests

**Comment by pyence** [comment]
Alright. Will do!
