### ISSUE TITLE
Spider: Laborers' & Retirement Board Employees' Annuity & Benefit Fund

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#667]
URL: http://www.labfchicago.org/agendas-minutes/
Spider Name: `chi_labor_retirement_fund`
Agency Name: Laborers' & Retirement Board Employees' Annuity & Benefit Fund

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by sfmajors373** [comment]
I'm going to try to work on this one.

**Comment by pjsier** [comment]
Closed by #686
