### ISSUE TITLE
Spider: Chicago Midway Noise Compatibility Commission

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#670]
URL: https://www.flychicago.com/community/MDWnoise/AdditionalResources/pages/default.aspx
Spider Name: `chi_midway_noise`
Agency Name: Chicago Midway Noise Compatibility Commission

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by bendiller** [comment]
Hi, I'd love to implement this one! I've got experience with Scrapy and can probably have a PR ready by the end of the weekend.

**Comment by pjsier** [comment]
@bendiller great! Feel free to reach out with any questions

**Comment by pjsier** [comment]
Closed by #838
