### ISSUE TITLE
Spider: Policemen's Annuity and Benefit Fund of Chicago

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#674]
URL: http://www.chipabf.org/ChicagoPolicePension/MonthlyMeetings.html
Spider Name: `chi_police_retirement`
Agency Name: Policemen's Annuity and Benefit Fund of Chicago

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by mattpair** [comment]
Hi, I am working on this one.

**Comment by pjsier** [comment]
Closed by #725
