### ISSUE TITLE
Spider: Cook County Medical Examiner's Advisory Committee

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#677]
URL: https://www.cookcountyil.gov/service/medical-examiners-advisory-committee
Spider Name: `cook_medical_examiner`
Agency Name: Cook County Medical Examiner

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by Anphisa** [comment]
@pjsier I would like to try this one. Is it still open? It would be my first open source contribution, so I might need some guidance.

**Comment by pjsier** [comment]
@Anphisa it's all yours! You can reach out here or on Slack if you have any other questions.

**Comment by Anphisa** [comment]
Will do! Thank you!

**Comment by pjsier** [comment]
Closed by #705
