### ISSUE TITLE
Spider: Chicago Cook Workforce Partnership

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#679]
URL: http://www.workforceboard.org/events-calendar/
Spider Name: `cook_workforce`
Agency Name: Chicago Cook Workforce Partnership

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by ElijahLawson** [comment]
I'd love to help out on this one if it's not taken!

**Comment by pjsier** [comment]
@ElijahLawson from looking at this a bit more, they haven't posted any meetings in a while. I'll probably close this, but you're welcome to take one of the other scrapers! There are a good amount of them that were initially claimed but are inactive so you can comment on any that seem interesting
