### ISSUE TITLE
Spider: Illinois Aging Advisory Council

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#680]
URL: https://www2.illinois.gov/aging/PartnersProviders/OlderAdult/Pages/acmeetings.aspx
Spider Name: `il_aging_advisory_council`
Agency Name: Illinois Aging Advisory Council

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by allenjhuang** [comment]
On it!

**Comment by ElijahLawson** [comment]
If this is currently inactive, I can get working on it.

**Comment by pjsier** [comment]
@ElijahLawson sounds good!

**Comment by shafique18** [comment]
can I work on it
please let me know what things need to scrape from the given site

**Comment by pjsier** [comment]
@shafique18 sounds good! Everything you need to get started should be in the development documentation https://cityscrapers.org/docs/development/

**Comment by luchiago** [comment]
Is this issue still need help?

**Comment by pjsier** [comment]
@luchiago assigning you here, @shafique18 let me know if you're still working on it but according to our contributing guidelines we sometimes need to reassign issues if they've been inactive for more than 30 days

**Comment by luchiago** [comment]
@pjsier I made a mistake, I wrote the wrong issue. Is the #808, because the link of this issue seems broken. Check my comment at #808.

**Comment by erik-kristofer-anderson** [comment]
This looks available, so I'd like to claim it.
Within a week, I'll come back here and comment on my progress. (If it turns out I'm in over my head I'll bow out at that point.)

**Comment by pjsier** [comment]
@erik-kristofer-anderson sounds good!

**Comment by erik-kristofer-anderson** [comment]
@pjsier I'm going to bow out at this point. Please mark this as un-claimed.

**Comment by pjsier** [comment]
thanks for the heads up!

**Comment by nick-symon** [comment]
@pjsier Hi! I'd like to claim this issue and begin work on it!

**Comment by pjsier** [comment]
@nick-symon sounds good!

**Comment by pjsier** [comment]
Closed by #944, thanks @nick-symon!
