### ISSUE TITLE
Spider: Illinois Sports Facilities Authority

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#681]
URL: https://www.isfauthority.com/governance/board-meetings/
Spider Name: `il_sports_facilities_authority`
Agency Name: Illinois Sports Facilities Authority

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by jamesarnall** [comment]
If unclaimed, I'll take this one on. Let me know if there's anything special about this particular site I need to know.

**Comment by pjsier** [comment]
It's all yours! The start times of past meetings aren't listed so it's probably safest to default to 10AM from a quick look, but otherwise it seems pretty straightforward

**Comment by chandranathr** [comment]
Can I help with this one?

**Comment by pjsier** [comment]
@chandranathr it's been inactive for a while, so go for it!

**Comment by chandranathr** [comment]
Due to current personal issues, I do not have the time to work on this bug. Apologies for your time.

**Comment by zybex86** [comment]
If unclaimed I'll have a go ;)

**Comment by pjsier** [comment]
@zybex86 go for it!

**Comment by zybex86** [comment]
Almost finished it - need to test it, as the author of the site has done some CRAZY HTML bindings... Also, should I scrape the most recent meetings? There is a meeting not mentioned in the list at the bottom...

**Comment by pjsier** [comment]
@zybex86 great! We should scrape the past few years of meetings here, are there any meetings you're referring to in particular? Might be worth adding a check in the loop that the meeting is within the past 2 years or so before yielding it though

**Comment by zybex86** [comment]
I'm referring to the 2-3 meetings in the h2 tags that start with days of the week... They are written just before the `meetings and agendas`. The others are ones in this year and prior. Also the full address is in those above (as it implies that sometimes the meeting is in a different place, but I think the extra files point to that)

**Comment by pjsier** [comment]
Yeah, I think those meetings are a high priority, and the address being at the top of the page is pretty common. We've used [`_validate_location`](https://cityscrapers.org/docs/development/#location) functions for that in the past to make sure that it hasn't changed

**Comment by zybex86** [comment]
I think I finished this. Can sb check the issue?

**Comment by d-glenz** [comment]
Can I help with this spider?

**Comment by pjsier** [comment]
@d-glenz all yours!

**Comment by pjsier** [comment]
Closed by #985, thanks @d-glenz!
