### ISSUE TITLE
Spider: Detroit Promise Zone Authority

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#698]
URL: https://detroitmi.gov/Calendar-and-Events
Spider Name: `det_promise_zone`
Agency Name: Detroit Promise Zone Authority

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

This scraper is part of the general Detroit website which does a good job standardizing meeting information so most of the work is done for you in [`DetCityMixin`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/mixins/det_city.py).

To pull most of the information for a general detroitmi.gov scraper, you need to go to the [events page](https://detroitmi.gov/Calendar-and-Events), filter for the agency in the Government select field, and then get the ID that shows up next to `term_node_tid_depth_1=` on the results page URL.

Then, to pull any related documents, go the the [documents page](https://detroitmi.gov/documents), look for relevant document categories in the Government autocomplete field, filter for them, and then pull the ID from the parameter in the results page URL that follows `field_department_target_id_1`. On initial filter, it will pull in a label too (ex. for the City Planning Commission it shows `City+Planning+Commission+Minutes+(3761)`) but you only need the number in parentheses.

Once you've included that information, you can override methods like `_parse_title` if the defaults aren't right, and you'll still need to implement `_parse_classification`. See [`det_city_planning`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_city_planning.py) or [`det_zoning_appeals`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_zoning_appeals.py) for some examples

**Comment by wtkwon** [comment]
If this is unclaimed. I would like to work on it.

**Comment by pjsier** [comment]
@wtkwon all yours!

**Comment by WhatAreYouSaying** [comment]
Is this issue claimed or finished now?

**Comment by pjsier** [comment]
@WhatAreYouSaying this one is available, but it's all yours if you want it

**Comment by WhatAreYouSaying** [comment]
@pjsier 
I try to search in the website manually, but all I got was results not found.
Is there any problem with my approach?

**Comment by pjsier** [comment]
Some of these might not actually have any events on the site, so you're welcome to take a different issue if they aren't showing up

**Comment by pjsier** [comment]
No info online, closing
