### ISSUE TITLE
Spider: Detroit Historic District Commission

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#700]
URL: https://detroitmi.gov/Calendar-and-Events
Spider Name: `det_historic_district`
Agency Name: Detroit Historic District Commission

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

This scraper is part of the general Detroit website which does a good job standardizing meeting information so most of the work is done for you in [`DetCityMixin`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/mixins/det_city.py).

To pull most of the information for a general detroitmi.gov scraper, you need to go to the [events page](https://detroitmi.gov/Calendar-and-Events), filter for the agency in the Government select field, and then get the ID that shows up next to `term_node_tid_depth_1=` on the results page URL.

Then, to pull any related documents, go the the [documents page](https://detroitmi.gov/documents), look for relevant document categories in the Government autocomplete field, filter for them, and then pull the ID from the parameter in the results page URL that follows `field_department_target_id_1`. On initial filter, it will pull in a label too (ex. for the City Planning Commission it shows `City+Planning+Commission+Minutes+(3761)`) but you only need the number in parentheses.

Once you've included that information, you can override methods like `_parse_title` if the defaults aren't right, and you'll still need to implement `_parse_classification`. See [`det_city_planning`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_city_planning.py) or [`det_zoning_appeals`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_zoning_appeals.py) for some examples

**Comment by cascio** [comment]
Currently working on this one, should have a PR up soon!

**Comment by cascio** [comment]
I think I got it, @pjsier, please review.

One question: [`det_city_planning`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_city_planning.py) and [`det_zoning_appeals`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_zoning_appeals.py) do not include the `agency_cal_id` in the `agency_doc_id` list although the `agency_cal_id` value is an option when filtering for the agency name on on the [documents page](https://detroitmi.gov/documents). Is this intentional?

You'll notice that in my PR for [`det_historic_district`](https://github.com/City-Bureau/city-scrapers/pull/706/files#diff-258833983c5944115534a911d0c406e6) I am including the `agency_cal_id` value in the `agency_doc_id` list. Let me know if I should adjust to match [`det_city_planning`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_city_planning.py) and [`det_zoning_appeals`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_zoning_appeals.py) or vice versa.

**Comment by pjsier** [comment]
@cascio taking a look now. For the `agency_cal_id` question, I was mostly going off of what seemed to have relevant documents (primarily agendas and minutes) for the agencies. I'd have to check again to be sure, but from what I remember those IDs were options but didn't seem to return anything. I think if it seems to be returning helpful documents it doesn't hurt to include it there

**Comment by pjsier** [comment]
Closed by #706, it looks like it's pulling the right documents

**Comment by cascio** [comment]
Thanks for the merge, @pjsier. On this point...

> @cascio taking a look now. For the `agency_cal_id` question, I was mostly going off of what seemed to have relevant documents (primarily agendas and minutes) for the agencies. I'd have to check again to be sure, but from what I remember those IDs were options but didn't seem to return anything. I think if it seems to be returning helpful documents it doesn't hurt to include it there

...I think [`det_city_planning`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_city_planning.py) and [`det_zoning_appeals`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_zoning_appeals.py) can be updated to include more `agency_doc_id`s. For example, the base ["City Planning Commission"](https://detroitmi.gov/documents?name=&field_department_target_id=&field_department_target_id_1=City+Planning+Commission+%281591%29&field_description_value=) id returns things like proposed funding budgets, bylaws and zoning classification documents. Another example, the base ["Board of Zoning Appeals"](https://detroitmi.gov/documents?name=&field_department_target_id=&field_department_target_id_1=Board+of+Zoning+Appeals+%281536%29&field_description_value=) id currently only returns the Board of Zoning Appeal's Rules and Procedures document.

If these are things that you want to scrape, I'll update [`det_city_planning`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_city_planning.py) and [`det_zoning_appeals`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/det_zoning_appeals.py) accordingly and send another PR.

**Comment by pjsier** [comment]
The only documents that get associated to meetings with the current Detroit setup are ones with dates corresponding to meetings in the title, so I think we should be good for now, but thanks for taking a closer look at that @cascio
