### ISSUE TITLE
Spider: Chicago Infrastructure Trust

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#717]
URL: http://chicagoinfrastructure.org/public-records/scheduled-meetings/
Document URL: http://chicagoinfrastructure.org/public-records/meeting-records-2/
Spider Name: `chi_infrastructure_trust`
Agency Name: Chicago Infrastructure Trust

The times aren't provided, so it's fine to default to midnight here. The main thing we're interested in is the next upcoming meeting and the past documents

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by channiemills** [comment]
HI @pjsier, I'd like to take a stab at this one. Do we know if the location for this one is constant?

**Comment by pjsier** [comment]
@channiemills sounds great! I think we have to assume it's constant since they haven't posted much, so I would go with the Metropolitan Planning Council address listed in the agendas

**Comment by pjsier** [comment]
Closed by #730, thanks @channiemills!
