### ISSUE TITLE
Spider: Chicago State University

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#718]
URL: https://www.csu.edu/boardoftrustees/dates.htm
Spider Name: `chi_state_university`
Agency Name: Chicago State University

Meeting title can always be "Board of Trustees" (unless there are committees). We also want to scrape the agendas, minutes, and transcripts here if possible

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by jartsavor** [comment]
I am going to give this a shot.

Also, I went through the [development](https://cityscrapers.org/docs/development/) docs, and I had some trouble at the automated test sections (for both pipenv and virtualenv). I kept getting an `UnicodeDecodeError` when running `pytest`. It turns out that I needed to add an `encoding='utf8'` argument to the `return open(file_path, 'r').read()` of line 37 in [tests/utils.py](https://github.com/City-Bureau/city-scrapers/blob/709d7c9536f030e5e2a5e0c6829d46de743bad86/tests/utils.py). Is this something that I should bring up as an issue or could this just be unique on my end? I have a windows 10 machine.

**Comment by pjsier** [comment]
@jartsavor sounds great! And feel free to just include that in this PR, we've addressed it elsewhere but must have missed that section since we've deprecated that module in favor of `city_scrapers_core.utils`

**Comment by jartsavor** [comment]
@pjsier okay will do, and thank for the quick reply.

**Comment by jartsavor** [comment]
I have an issue related to an unknown date/time for a meeting. What should I do when there is a rescheduled time indicated on the website? For instance below,

Friday, March 1, 2019 
-RESCHEDULED to: TBD

is shown on the website, and I'm not sure  how to handle it.
I have checked [this](https://github.com/City-Bureau/city-scrapers/issues/88) issue, but it doesn't address this specific conflict.

**Comment by pjsier** [comment]
@jartsavor any time something is rescheduled we're just considering it cancelled, so you could pass the text for the meeting (including where "RESCHEDULED" would be) to the `get_status` method in the `text` kwarg like this https://github.com/City-Bureau/city-scrapers/blob/bc1d5ff6163517df4e198dcd6161754a0a326d7c/city_scrapers/spiders/chi_schools.py#L42

**Comment by bwalterscoding** [comment]
> @jartsavor sounds great! And feel free to just include that in this PR, we've addressed it elsewhere but must have missed that section since we've deprecated that module in favor of `city_scrapers_core.utils`

Speaking of 'city_scrapers_core', when I was practicing along with the documentation, I tried to run a scraper and I received an error message saying  'No module named 'city_scrapers_core' found'.  Where should that file be?

My Steps:
* I forked the project
* Clone the repository from my github
* Successfully created a virtual env using pipenv and activated it
* pip installed scrappy and pypiwin32
* Tried to run the scraper and received error message mentioned above.

I'm very fascinated in this project and look forward to learning more about it.

**Comment by pjsier** [comment]
@bwalterscoding when you say you `pip installed` did you run `pipenv install`? That should install all dependencies so that you don't have to install them individually

**Comment by bwalterscoding** [comment]
That seemed to be the issue, thanks a bunch.

**Comment by luchiago** [comment]
Can I grab this one? @pjsier

**Comment by pjsier** [comment]
All yours! @luchiago

**Comment by Rhysoshea** [comment]
Hi @pjsier, could I have a go at this one if it has been reopened?

**Comment by pjsier** [comment]
Sure! Assigning you now

**Comment by pjsier** [comment]
Closed by #974, thanks @Rhysoshea!
