### ISSUE TITLE
Spider: Illinois Opioid Crisis Response Advisory Council

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#719]
URL: https://www.dhs.state.il.us/page.aspx?item=97186
Links URL: https://www.dhs.state.il.us/page.aspx?item=104682
Spider Name: `il_opioid_response`
Agency Name: Illinois Opioid Crisis Response Advisory Council

It's important that we pull the URLs here, and it's safe to assume that the time and location are constant

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by channiemills** [comment]
Hi @pjsier - I'd like to contribute and will take a look at this issue.

**Comment by pjsier** [comment]
@channiemills sounds great!

**Comment by pjsier** [comment]
Closed by #724
