### ISSUE TITLE
Spider: Cook County North Shore Mosquito Abatement District

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#729]
URL: https://www.nsmad.com/news-events/board-meetings/
Spider Name: `cook_north_shore_mosquito`
Agency Name: Cook County North Shore Mosquito Abatement District

Meeting title can always be "Board of Trustees" (unless there are committees). It can default to the location listed, but should verify that the location exists first (see [`chi_labor_retirement_fund`](https://github.com/City-Bureau/city-scrapers/blob/a863812f1fa3347e854a694672999229e8dbc05c/city_scrapers/spiders/chi_labor_retirement_fund.py#L27) for an example of this)

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by mattpair** [comment]
I am working on this one

**Comment by pjsier** [comment]
Closed by #741, thanks @mattpair!
