### ISSUE TITLE
Spider: Cook County Housing Authority

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#771]
URL: http://thehacc.org/events/
Doc URL: http://thehacc.org/about/
Spider Name: `cook_housing`
Agency Name: Cook County Housing Authority

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by aminamos** [comment]
Hi, I'm very new to Python and open source contributing in general. Currently going through [the guide](https://cityscrapers.org/docs/development/#contribute) and will start looking at this. Thank you!

**Comment by pjsier** [comment]
@aminamos sounds great, feel free to reach out with any questions!

**Comment by pg** [comment]
@pjsier @aminamos Any chance I could take this one over for #hacktoberfest?

**Comment by pjsier** [comment]
@pg all yours if there isn't a response for a day or so!

**Comment by aminamos** [comment]
@pg definitely, happy hacking!

**Comment by pjsier** [comment]
Closed by #862
