### ISSUE TITLE
Spider: North River Expanded Mental Health Services Program and Governing Commission

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#772]
URL: http://www.northriverexpandedmentalhealthservicescommission.org/index.html
Doc URL: http://www.northriverexpandedmentalhealthservicescommission.org/minutes.html
Spider Name: `chi_north_river_mental_health`
Agency Name: North River Expanded Mental Health Services Program and Governing Commission

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by anadolski** [comment]
Hi! This is a cool project. I'm new to contributing to open-source projects and web-scraping, but I'd like to give this issue a shot.

**Comment by pjsier** [comment]
@anadolski sounds great! Feel free to reach out with any questions

**Comment by EmefaA** [comment]
Hi @pjsier! I am interested in helping out with this project.

**Comment by pjsier** [comment]
@EmefaA all yours since it looks like it's been inactive!

**Comment by anadolski** [comment]
Sorry for dropping the ball here! My time for outside projects has dropped
to about zero. Please do take this one over!

**Comment by EmefaA** [comment]
Hi @pjsier I tried to create a barebones spider but I got a ModuleNotFoundError: No module named 'city_scrapers_core'. How can I fix this? Thanks!

**Comment by pjsier** [comment]
@EmefaA could you tell me some of the steps you took to set up the scrapers? And did you go through the steps in the [documentation](https://cityscrapers.org/docs/development/)? We've had some people run into that from using Python 2

**Comment by EmefaA** [comment]
Hi @pjsier I updated to Python 3.7 but for some reason version 2.7 is showing when I check the version. I will try to fix that and get back to you. Thanks!

**Comment by EmefaA** [comment]
Hi @pjsier I changed my path to use Python 3.7 but I am still getting the same error.  

(city-scrapers) ➜  city-scrapers git:(0772-spider-chi_north_river_mental_health) scrapy genspider chi_north_river_mental_health "North River Expanded Mental Health Services Program and Governing Commission" http://www.northriverexpandedmentalhealthservicescommission.org
Traceback (most recent call last):
  File "/Users/ea/anaconda3/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/Users/ea/anaconda3/lib/python3.7/site-packages/scrapy/cmdline.py", line 125, in execute
    cmds = _get_commands_dict(settings, inproject)
  File "/Users/ea/anaconda3/lib/python3.7/site-packages/scrapy/cmdline.py", line 56, in _get_commands_dict
    cmds.update(_get_commands_from_module(cmds_module, inproject))
  File "/Users/ea/anaconda3/lib/python3.7/site-packages/scrapy/cmdline.py", line 33, in _get_commands_from_module
    for cmd in _iter_command_classes(module):
  File "/Users/ea/anaconda3/lib/python3.7/site-packages/scrapy/cmdline.py", line 22, in _iter_command_classes
    for module in walk_modules(module_name):
  File "/Users/ea/anaconda3/lib/python3.7/site-packages/scrapy/utils/misc.py", line 65, in walk_modules
    mod = import_module(path)
  File "/Users/ea/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'city_scrapers_core'

**Comment by pjsier** [comment]
We don't have a ton of info on working with anaconda, so that could be part of it. Are you still creating a virtual environment and running the `genspider` command from inside of it?

**Comment by EmefaA** [comment]
Oh ok. Yes I am creating a virtual environment and running genspider command from inside of it. Should I try it with a different issue number and see if I get the same error?

**Comment by pjsier** [comment]
A different issues shouldn't make a difference, so you don't need to do that. When you run `python -V` does it show the version of Python you're expecting? And did you install with `pipenv` or just `pip`? It might be worth trying `pip install -r requirements.txt` inside the virtual environment

**Comment by EmefaA** [comment]
Python version is 3.7.3 

I installed pipenv install --dev --ignore-pipfile --three

Ok I will try pip install -r requirements.txt inside the virtual environment

**Comment by EmefaA** [comment]
Hi @pjsier I got this message when I tried to pip install the requirements text. I will do some research to see how I can overcome this

(city-scrapers) ➜  city-scrapers git:(0772-spider-chi_north_river_mental_health)pip install -r requirements.txt
[1]    19028 abort      pip install -r requirements.txt

**Comment by maykonmenezes** [comment]
is it still available? I'm interested in helping out with this one.

**Comment by EmefaA** [comment]
Hi @maykonmenezes I am still working on this project

**Comment by alderocas** [comment]
Hi Patrick, I'd like to work on this

**Comment by pjsier** [comment]
@alderocas sounds good! I'll mark this claimed

**Comment by alderocas** [comment]
@pjsier you also need the "upcoming" meeting on the main page parsed, right? or just those on the minutes page?

**Comment by pjsier** [comment]
We're interested in both, and the minutes are important because we want to make sure we're getting relevant documents

**Comment by pjsier** [comment]
Closed by #970, thanks @alderocas!

**Comment by alderocas** [comment]
@pjsier Happy to help!

Is there anything else that needs to be done ASAP?

**Comment by pjsier** [comment]
Nothing urgent, but feel free to take a look at open issues!
