### ISSUE TITLE
Spider: Governors State University

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#797]
URL: http://www.govst.edu/About/Board_of_Trustees/Board_of_Trustees_Meeting_Dates_and_Minutes/
Spider Name: `il_governors_state_university`
Agency Name: Governors State University
Meeting Title: Board of Trustees (unless it's a committee meeting)

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by nikhilrbaradwaj** [comment]
hey you still need help with this? I just went through the installation guide successfully.

**Comment by pjsier** [comment]
Yep, if you’re interested it’s all yours!

**Comment by nikhilrbaradwaj** [comment]
what's the significance of "meeting title"? you still want me to crawl the whole webpage right?

**Comment by pjsier** [comment]
That’s just the default for the title of the meetings that should be returned unless a different one is provided

**Comment by channiemills** [comment]
I'll take a stab at this one if it's all good!

**Comment by nikhilrbaradwaj** [comment]
go ahead, my bad on not being organized about this.

**Comment by channiemills** [comment]
Hmm it appears the link is no longer available.

**Comment by pjsier** [comment]
Gotcha, might be a temporary thing so we can leave it alone for now

**Comment by timsmaluk** [comment]
This is the new link: https://www.govst.edu/BOT-Meetings/
I am new to OSS, but could I try this one?

**Comment by pjsier** [comment]
@timsmaluk all yours!

**Comment by jmelot** [comment]
I can do this one next weekend!

**Comment by pjsier** [comment]
@jmelot sounds great! Assigning you now

**Comment by pjsier** [comment]
Closed by #975, thanks @jmelot!
