### ISSUE TITLE
Spider: Illinois Lottery Control Board

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#798]
URL: https://www.illinoislottery.com/illinois-lottery/lottery-control-board
Spider Name: `il_lottery`
Agency Name: Illinois Lottery Control Board

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by ozzysChiefDataScientist** [comment]
I'd like to work on this!

**Comment by pjsier** [comment]
@ozzysChiefDataScientist sounds great! It's all yours

**Comment by pjsier** [comment]
Closed by #820, thanks @ozzysChiefDataScientist!
