### ISSUE TITLE
Spider: Detroit Wayne Mental Health Authority

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#800]
URL: https://www.dwmha.com/about-us/dwmha-authority-board/board-directors-2017-committee-and-board-meeting-schedule/
Spider Name: `det_mental_health_authority`
Agency Name: Detroit Wayne Mental Health Authority

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by andrew-sharpl** [comment]
Hey, I've started working on this scraper

**Comment by pjsier** [comment]
@andrew-sharpl sounds great! Feel free to reach out with any questions

**Comment by andrew-sharpl** [comment]
Am I allowed to use libraries that aren't already dependencies? I would like to use beautifulsoup for parsing the html

**Comment by pjsier** [comment]
@andrew-sharpl Scrapy has a similar setup built in for CSS and XPath selectors, so I think we should stick with that for now

**Comment by andrew-sharpl** [comment]
Hey, I'm in the process of moving right now and haven't had any time to
work on it. I don't think I'll be able to finish it. If you want help
writing any of the functions or tests let me know.

**Comment by pjsier** [comment]
@andrew-sharpl no problem! I merged a PR with it yesterday, but feel free to pick up another scraper if you're interested
