### ISSUE TITLE
Spider: Illinois Board of Examiners

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#801]
URL: https://www.ilboe.org/board-information/board-meetings/
Spider Name: `il_board_of_examiners`
Agency Name: Illinois Board of Examiners

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by mahesh174** [comment]
Hi, Can I work on this issue?

**Comment by pjsier** [comment]
@mahesh174 sure! Feel free to reach out with any questions

**Comment by pjsier** [comment]
Closed by #832
