### ISSUE TITLE
Spider: Illinois Commission on Police Professionalism

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#802]
URL: https://www.isp.state.il.us/media/openmtgs.cfm
Spider Name: `il_police_professionalism`
Agency Name: Illinois Commission on Police Professionalism

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by sameerchandra** [comment]
Hi, is this issue still open? I would like to have a go at this. Thanks!

**Comment by pjsier** [comment]
Yep, all yours if you’re interested!

**Comment by pjsier** [comment]
Closed by #830
