### ISSUE TITLE
Spider: Illinois Investment Policy Board

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#803]
URL: https://www2.illinois.gov/sites/iipb/Pages/MeetingInformation.aspx
Spider Name: `il_investment_policy`
Agency Name: Illinois Investment Policy Board

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by wraikes** [comment]
Hello, I'd like to work on this issue!

**Comment by pjsier** [comment]
@wraikes sounds good, all yours!

**Comment by pg** [comment]
@wraikes Are you working on this issue? If not, I would like to take it on. How does that sound @pjsier?

**Comment by pjsier** [comment]
@pg if you don't hear back in a day or so that works for me!

**Comment by wraikes** [comment]
@pg sorry for the delay, I'm still working on this one, thank you!

**Comment by pg** [comment]
Oh, shoot! I just saw this... I got excited and was eager to help out for #hacktoberfest. I ended up working on this one first to get an understanding of the project. I think I have something working.

**Comment by pjsier** [comment]
@wraikes sorry about the miscommunication here, but happy to help you get started on another spider if you're still interested! And I'll take a look at your PR, @pg

**Comment by wraikes** [comment]
@pjsier no worries! I'll just work on another issue.  thank you.

**Comment by pjsier** [comment]
Closed by #858, thanks @pg!
