### ISSUE TITLE
Spider: Illinois Liquor Control Commission

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#804]
URL: https://www2.illinois.gov/ilcc/Divisions/Pages/Legal/Hearing-Schedule-for-Chicago-IL-and-Springfield-IL.aspx
Doc URL: https://www2.illinois.gov/ilcc/Divisions/Pages/Legal/Meeting-minutes.aspx
Spider Name: `il_liquor_control`
Agency Name: Illinois Liquor Control Commission

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by kwonhur** [comment]
Can I take on this issue if it is still available? Thanks!

**Comment by pjsier** [comment]
@kwonhur all yours!
