### ISSUE TITLE
Spider: Illinois Pollution Control Board

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#805]
URL: https://pcb.illinois.gov/ClerksOffice/Calendar
Doc URL: https://pcb.illinois.gov/ClerksOffice/MeetingMinutes
Spider Name: `il_pollution_control`
Agency Name: Illinois Pollution Control Board

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

We should pull hearings and board meetings from the calendar for the past year (so July-July, etc) and then match them to minutes (if available) on the minutes page. We'll need to pull the info out of the `iframe` source there

**Comment by samw430** [comment]
Is this issue open? I'd like to try it out if it is.

**Comment by pjsier** [comment]
@samw430 yep, it's open and all yours if you're interested

**Comment by samw430** [comment]
Perfect.  I'll get on it

**Comment by bendiller** [comment]
Hi @pjsier, may I take this one? @samw430 are you still intending to work on this?

**Comment by pjsier** [comment]
@bendiller all yours if it's inactive!

**Comment by AmiMappy** [comment]
I would like to work on it (if it is still inactive). Can I?

**Comment by bendiller** [comment]
@AmiMappy I've begun working on this yesterday.

**Comment by AmiMappy** [comment]
Thanks for letting me know.

**Comment by bendiller** [comment]
Hi Patrick - 

Would you please clarify your comment: `"We should pull hearings and board meetings from the calendar for the past year (so July-July, etc)"`? I've got a couple questions.

1. Was this included as a convenience to the developer creating the spider or for some other reason?

2. The way it's worded suggests that you don't want this spider to return details about meetings scheduled in the future, only those that have already occurred. This doesn't seem to match what I know about the project, which has me confused.

Thanks!

**Comment by pjsier** [comment]
Sorry for the confusion! You don't need to pull minutes all the way back to 2000 even though they have them, so that was mostly intended as a convenience thing.

It should still definitely return details from a few (2-4) months into the future whether they have documents or not

**Comment by bendiller** [comment]
Ah okay, that makes more sense, thanks!

**Comment by pjsier** [comment]
Closed by #882
