### ISSUE TITLE
Spider: Illinois Sex Offender Management Board

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#807]
URL: https://www2.illinois.gov/idoc/Pages/SexOffenderManagementBoard.aspx
Spider Name: `il_sex_offender_management`
Agency Name: Illinois Sex Offender Management Board

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by BobbyKarabinakis** [comment]
Hi There,

i would like to work on this issue

**Comment by pjsier** [comment]
@BobbyKarabinakis sounds good!

**Comment by mmachado95** [comment]
Hi, if this is still up for grabs I would like to start working on it.

**Comment by pjsier** [comment]
@BobbyKarabinakis are you still working on this? If not it's all yours, @mmachado95

**Comment by mmachado95** [comment]
@pjsier Can I try to move forward with this?

**Comment by pjsier** [comment]
@mmachado95 go for it!

**Comment by mmachado95** [comment]
Hey @pjsier quick question the meetings location and time is provided by the pdf that opens up after you click the meeting link.
In this case do I try to get that data from the PDF or do we ignore it?

**Comment by pjsier** [comment]
Ideally I think we should try and parse these PDFs since I'm also seeing cancellation notices inside https://www2.illinois.gov/idoc/Documents/SOMB%20Meeting%20Agenda%202019%20August.pdf. It might only be necessary to actually parse the agenda content since the minutes content shouldn't be different

**Comment by mmachado95** [comment]
Yeah some even have cancellation notes. 
Thanks for the clarification 👍  will look into parsing the pdf.

**Comment by pjsier** [comment]
We've been using PyPDF2 for that mostly, and there's an example in `chi_human_relations`

**Comment by mmachado95** [comment]
Oh that will make it easier, thanks for the help!

**Comment by luchiago** [comment]
Is this issue still need help?

**Comment by mmachado95** [comment]
Hey sorry I've been a bit delayed with this issue, work stuff got a bit in the way. 
I'm working on it still

**Comment by luchiago** [comment]
@mmachado95 that's ok, no problem. Good job.

**Comment by cvafaian** [comment]
Hi, I'd like to work on this if it's still available.

**Comment by pjsier** [comment]
@cvafaian sure! Assigning you now

**Comment by cvafaian** [comment]
Hello! 
I ran into an issue where the latest meeting is not in a PDF format but rather is a link to a WebEx meeting (September 16, 2020 – WebEx Meeting). Upon clicking in I quickly realized that I would need an Illinois.gov employee account, which I do not have. I can still get the information that a meeting happened on the date, but I can no longer determine anything else pertaining to that one meeting. How would you like me to proceed?

**Comment by pjsier** [comment]
@cvafaian thanks for looking into this, and sorry you ran into that! If it's alright with you, I think we can still parse the time of day.

If you add `custom_settings = {"ROBOTSTXT_OBEY": False}` to your spider (like in [`chi_ssa_34`](https://github.com/City-Bureau/city-scrapers/blob/02dc0e6af6654b15898f6ea3d1b362ba542258e4/city_scrapers/spiders/chi_ssa_34.py#L14)) and yield a new `scrapy.Request` for the WebEx link, it looks like it'll give you a 200 response with an HTML page.

From trying it out in `scrapy shell` there's a `script` tag with the type `application/ld+json` which contains metadata in JSON of some of the meeting details. We have an example of parsing JSON from a tag like that in [`chi_ssa_25`](https://github.com/City-Bureau/city-scrapers/blob/c42620480f9184ca74885e2a3c6ef576faba3eb7/city_scrapers/spiders/chi_ssa_25.py#L39-L41). Let me know how that sounds, thanks!

**Comment by cvafaian** [comment]
@pjsier Thanks for the detailed help! With it I was able to successfully extract the time and day of the meeting, and I have since pushed the changes :)

**Comment by pjsier** [comment]
Closed by #993, thanks @cvafaian!

**Comment by cvafaian** [comment]
Thank you @pjsier for being so approachable and welcoming! This was my first time working on an open source project and I really appreciated how kind, helpful, and prompt you were. All the best!
