### ISSUE TITLE
Spider: Illinois State Board of Elections

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#808]
URL: https://www.elections.il.gov/AboutTheBoard/Agenda.aspx
Doc URL: https://www.elections.il.gov/AboutTheBoard/MeetingMinutesAll.aspx
Spider Name: `il_elections`
Agency Name: Illinois State Board of Elections

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by raufabr** [comment]
Is this issue still open? I would like to have a go at this.

**Comment by pjsier** [comment]
@raufabr yep, all yours if you're interested!

**Comment by akaysh** [comment]
@raufabr are you still working on this? If not, I would like to work on this.

**Comment by pjsier** [comment]
@akaysh I think you're good to work on this, thanks!

**Comment by AmiMappy** [comment]
Can I give it a go?

**Comment by pjsier** [comment]
Hi @AmiMappy, thanks for the interest in contributing! It looks like someone is working on this one, but you’re welcome to take a look at any of the issues that haven’t had any comments in a month or so. Let me know if you have any questions

**Comment by AmiMappy** [comment]
Thanks a lot.

**Comment by luchiago** [comment]
Is this issue still need help?

**Comment by pjsier** [comment]
@luchiago this and some of the other issues you commented on are open, but we ask that contributors only work on one scraper at a time. Is there one you're most interested in starting on?

**Comment by luchiago** [comment]
@pjsier I would like to work on #680.

**Comment by pjsier** [comment]
Gotcha, assigned here

**Comment by luchiago** [comment]
Thanks man.

**Comment by luchiago** [comment]
@pjsier The link seems broken. What should I do?

**Comment by pjsier** [comment]
Both links look fine to me, not sure where the error would be coming from

**Comment by luchiago** [comment]
@pjsier Should I crawl the docs from the `Doc URL`?

**Comment by luchiago** [comment]
@pjsier I'm facing trouble to crawl this site. Can I work in another spider?

**Comment by pjsier** [comment]
Sure, just comment on a spider you'd want to work on next

**Comment by BurakcanK** [comment]
Hi, I am fairly new to open-source projects but curious nevertheless, could I have a go if that's possible ?

**Comment by pjsier** [comment]
@BurakcanK all yours! Assigning you now

**Comment by pjsier** [comment]
Closed by #938
