### ISSUE TITLE
Spider: Chicago Special Service Area #61 Hyde Park

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#843]
URL: http://www.downtownhydeparkchicago.com/about/
Spider Name: chi_ssa_61
Agency Name: Chicago Special Service Area #60 Hyde Park

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by firejava** [comment]
going to give this one a shot

**Comment by firejava** [comment]
#860

**Comment by pjsier** [comment]
Closed by #861

**Comment by pg** [comment]
Hmm...I just noticed Agency Name lists `#60`, but spider name and the issue title list `#61`. I think the correct value is `#61`
