### ISSUE TITLE
Spider: Chicago Special Service Area #62 Sauganash

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#844]
URL: http://escc60646.com/our_events/
Spider Name: chi_ssa_62
Agency Name: Chicago Special Service Area #62 Sauganash

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by pg** [comment]
@pjsier I'd like to try this one next.

**Comment by saswat01** [comment]
i'd lik to grab it

**Comment by pg** [comment]
@saswat01 I’ve already started on it. Should have something shortly.

**Comment by saswat01** [comment]
ok !

**Comment by pjsier** [comment]
Closed by #883, thanks @pg!
