### ISSUE TITLE
Spider: Chicago Special Service Area #72 Austin

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#846]
URL: http://www.av72chicago.com/commissioners--meetings.html
Spider Name: `chi_ssa_72`
Agency Name: Chicago Special Service Area #72 Austin

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by doubledare704** [comment]
I'll take this

**Comment by pjsier** [comment]
Weird, it was up yesterday. You can use this Wayback Machine link for testing until it's back up https://web.archive.org/web/20190929023807/http://www.av72chicago.com/commissioners--meetings.html

**Comment by channiemills** [comment]
I'll work on this one!

**Comment by pjsier** [comment]
@doubledare704 are you still working on this? If not you're good to go @channiemills, looks like the site is back up

**Comment by pjsier** [comment]
Closed by #922, thanks @channiemills!
