### ISSUE TITLE
Spider: Illinois Department of Corrections Advisory Board

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#847]
URL: https://www2.illinois.gov/idoc/aboutus/advisoryboard/Pages/default.aspx
Spider Name: `il_corrections`
Agency Name: Illinois Department of Corrections Advisory Board

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

Some information will need to be parsed from PDFs, so it could be useful to look at [`chi_human_relations`](https://github.com/City-Bureau/city-scrapers/blob/fbddf7cf785f261ea1829706dd58fc7ea5777a9a/city_scrapers/spiders/chi_human_relations.py) for an example of how to handle this

**Comment by jairathnem** [comment]
I am working on this one. PDF documents for the different dates are inconsistent and don't always follow a format. Any suggestions on that?

**Comment by zuzaman** [comment]
I just wanted to check this issue and saw that the https://www2.illinois.gov/ website is not reachable. do you possible know if they moved to a new host?

**Comment by pjsier** [comment]
@zuzaman we've had issues with people outside of Illinois and/or the US accessing that URL. Not sure if that applies to you, but it's showing up for me still

**Comment by zuzaman** [comment]
@pjsier  Ok, thanks. Well then I will leave this issue as I am from the EU. :)

**Comment by SubtleHyperbole** [comment]
I am trying to see whether I could do this as my first contribution, but I’m running into a problem.  I follow the instructions you provided on cloning the git locally and then using pipenv to create a virtual environment on a new branch with this issue # in tfw format suggested, with all the necessary dependencies, 

I am running into two issues.  The first is that, at this point, I open up the spider file in my programming environment of choice, Jupiter notebook, and quickly discover that the dependencies installed in the virtual environment on the command line don’t apply to the Jupiter kernels I can create there.  Ok, so I try to instead open up the files in Atom but run into the same issue.

This led me to discover my 2nd issue.  I decided ok what if I just install the missing decencies so I can work on the code outside of the command terminal.  I see that I am missing city_scrapers_core but when I try to install that I see that I am missing a dependency called Legistar.  I try to install legistar and learn that it is not available me to Mac OSX users.  

I’m confused at this point bc as far as I could tell from what read our on the command line using pipenv, there weren’t any problems with the piplock file that I would assume should have thrown up a roadblock to creating the virtual environment — namely that legistar isn’t supported on Mac and that city_scrapers_core requires legistar — but maybe I missed it.

Assuming I didn’t miss it, why was pipenv able to install legistar and city_scrapers_core while I am unable to do so in any of the coding environments that I am familiar with using to actually write and debug code? 

Alternatively, is there a reasonable way to skip my usual software and edit the spider and test files from the command line interface inside the pipenv environment, including with an interpreter to actually run code to test things out, that wouldn’t be obnoxiously slow and non-color formatted?

**Comment by pjsier** [comment]
@SubtleHyperbole sorry about that! Not sure what the issue is with Atom, but we don't support Jupyter Notebooks specifically.

What issue are you running into on Atom? I can see Jupyter not including the dependencies, but I've run the repo on both Mac and Linux using VSCode, and if you're running the commands in a separate terminal that you enter with `pipenv shell` or prefix commands with `pipenv run` ([more info in the docs here](https://cityscrapers.org/docs/development/#install-dependencies)) it should find the dependencies regardless of your editor. Pipenv also just did a big update though, so not sure if that's causing anything

**Comment by SubtleHyperbole** [comment]
ohh so i can run the same virtual environment in other editors -- i would just need to actually enter them first?  Okay i'll try that.

I am still curious though about the legistar thing -- is legistar necessary to run city_scrapers_core? Perhaps the places I read that it doesn't support Mac OSX were old, and that now it does support it.  

I will check all these things out.  If I manage to get up and running, I would like to claim this issue as my first contribution and give it a shot.

**Comment by SubtleHyperbole** [comment]
nevermind I figured out how to install it.  For some reason legistar isn't on pypi, so you have to install it directly from git.  I didn't know that you could feed pip a url to a github location of a library and it would still install it.  Learn something new every day :)

**Comment by SubtleHyperbole** [comment]
in the following line of code:

test_response = file_response(
    join(dirname(__file__), "files", "il_corrections.html"),
    url="https://www2.illinois.gov/idoc/aboutus/advisoryboard/Pages/default.aspx",
)

where does the variable __file__ inside dirname() call supposed to come from? I cant find any source or reference to a class method of it anywhere and my interpreter is throwing an exception on that term specifically as being undefined.

**Comment by SubtleHyperbole** [comment]
So should the spider scrape and return just those meetings that have not yet happened?

Or should it pull past meetings and return data for those as well?

**Comment by pjsier** [comment]
We're interested in all meetings available, past and future as well as any documents like agendas or minutes that are attached

**Comment by SubtleHyperbole** [comment]
> @SubtleHyperbole sorry about that! Not sure what the issue is with Atom, but we don't support Jupyter Notebooks specifically.
> 
> What issue are you running into on Atom? I can see Jupyter not including the dependencies, but I've run the repo on both Mac and Linux using VSCode, and if you're running the commands in a separate terminal that you enter with `pipenv shell` or prefix commands with `pipenv run` ([more info in the docs here](https://cityscrapers.org/docs/development/#install-dependencies)) it should find the dependencies regardless of your editor. Pipenv also just did a big update though, so not sure if that's causing anything

Hi Pjsier -- I am looking at the website affiliated with this issue -- for the advisory board for the illinois department of corrections -- when I pull it up, it looks to me that they haven't been posting full meeting schedules since 2016.  There are some "advance notices" for individual meetings, but the most recent one of those is from January 2019.  

After that January 2019 meeting, they have agendas and minutes posted for the remaining 2019 meetings, but upon checking archive.org it looks like these things were not posted prior to the meeting occuring.  

Is this board just not doing what it is supposed to be doing re publishing info on their meetings ahead of time so that the public can attend?  I sent the head of the board an email asking what was up, but haven't received any response.  

As it stands, is this issue actually solvable, given the current state of the government entity's current posting practices?

**Comment by pjsier** [comment]
A lot of boards aren't publishing meetings as often as they're supposed to, but we're still interested in pulling their documents whether or not they're posting them in the required time frame since it's information that isn't collected anywhere else

**Comment by shf** [comment]
I am interested in this issue. Would you assign it to me?

**Comment by pjsier** [comment]
@shf thanks for the interest! We try to have contributors focus on one spider at a time though, so once your current PR is merged I'd be happy to. More info in [our contributing guidelines](https://github.com/City-Bureau/city-scrapers/blob/main/CONTRIBUTING.md#1-find-an-open-issue-to-work-on)

**Comment by shf** [comment]
Yeah, sure. Thanks for letting me know.

**Comment by fshih1** [comment]
This will be my first contribution! I will be more than happy to take on this issue!

**Comment by pjsier** [comment]
@fshih1 sounds great! Assigning you now

**Comment by fshih1** [comment]
> @fshih1 sounds great! Assigning you now

my sincerely apology that I wouldn't be having time to work on this anytime due to moving and found a job! Again, my deep apology. If anyone could pick it up that would be helpful!

**Comment by cherdeman** [comment]
@pjsier, I can take this one!

**Comment by pjsier** [comment]
@cherdeman great! I'll assign you

**Comment by cherdeman** [comment]
@pjsier - FYI that I opened a PR with a question about my Scrapy usage. basically I'm trying to return the text from the pdfs for each meeting for processing, but am ending up with a generator object instead. Certainly a Scrapy usage issue on my side, any suggestions to get the behavior I expect or rework to use the package more as intended?

**Comment by pjsier** [comment]
@cherdeman sure! Scrapy requests are made asynchronously, so if you want to guarantee you have data available for another method you'll need to make sure you're chaining callbacks so that they're called in the right order.

You can see an example of this in [`chi_human_relations`](https://github.com/City-Bureau/city-scrapers/blob/c42620480f9184ca74885e2a3c6ef576faba3eb7/city_scrapers/spiders/chi_human_relations.py#L29-L50) where the first request (in `start_urls`) goes to a department detail page. The `parse` method is the default callback, so the response from the detail page is checked there, and from there look for a PDF link to parse and `yield` a request to that link that will be handled by `_parse_schedule`. In `_parse_schedule` we handle the response body and then chain another request to `_parse_documents` now that we know the schedule details will be available and can be used to `yield` meetings.

From taking an initial look at your scraper, it looks like you could follow a similar pattern of first parsing all of the links, then `yield` a request to each meeting, pull the PDF, and then potentially `yield` back to the meeting (which is where this one might be a bit circular). Let me know if that's helpful! The Scrapy docs are also generally good, so if there's anything I can help with from those let me know

**Comment by cherdeman** [comment]
@pjsier thanks for response - figured it out with this and a second look. I've completed the PR with passing tests/style checks, not sure who to tag as a reviewer. Thanks and happy new year!

**Comment by pjsier** [comment]
Closed by #994, thanks @cherdeman!
