### ISSUE TITLE
Spider: Wayne State University

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#848]
URL: https://bog.wayne.edu/
Spider Name: `wayne_state_university`
Agency Name: Wayne State University
Meeting Title: Board of Governors

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by moisesjsanchez** [comment]
Hello, I am a first-time contributor.  Would it be okay for me to work on this?

**Comment by pjsier** [comment]
@moisesjsanchez all yours!

**Comment by DiegoCaraballo** [comment]
Hello @pjsier 
I would like to start working here.
Regards

**Comment by pjsier** [comment]
Sounds great! Assigning you now @DiegoCaraballo

**Comment by DiegoCaraballo** [comment]
The extraction includes everything?
![wayne](https://user-images.githubusercontent.com/21015263/84036707-f847a700-a973-11ea-9592-04ddeb5382c1.PNG)

**Comment by pjsier** [comment]
Yep, and we'll want to pull information from detail pages if available

**Comment by pjsier** [comment]
Moving to https://github.com/City-Bureau/city-scrapers-det/issues/1
