### ISSUE TITLE
Spider: Wayne County Airport Authority

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#849]
URL: https://www.metroairport.com/business/about-wcaa/board
Spider Name: `wayne_airport_authority`
Agency Name: Wayne County Airport Authority

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by Yeshwanthyk** [comment]
I would like to work on this?

**Comment by pjsier** [comment]
@Yeshwanthyk sounds good!

**Comment by pjsier** [comment]
Closing because this has been moved
