### ISSUE TITLE
Spider: Detroit Regional Convention Facility Authority

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#850]
URL: http://www.drcfa.org/upcoming-meetings
Spider Name: `det_regional_convention`
Agency Name: Detroit Regional Convention Facility Authority

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by udoedo** [comment]
Hi, can I work on this ?

**Comment by pjsier** [comment]
@udoedo go for it! Happy to answer questions here
