### ISSUE TITLE
Spider: Wayne County Local Emergency Planning Committee

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#853]
URL: https://www.waynecounty.com/departments/hsem/wayne-county-lepc.aspx
Spider Name: `wayne_local_emergency_planning`
Agency Name: Wayne County Local Emergency Planning Committee

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by Brian-Lee** [comment]
I'm interested is tackling this. I'n new BTW.

**Comment by pjsier** [comment]
@Brian-Lee all yours! Feel free to reach out with any questions

**Comment by Brian-Lee** [comment]
ty! I'm waiting to get my slack invite. Also, should my branch be named 0853-spider-wayne-county-lepc ?

**Comment by pjsier** [comment]
That works! The spider should keep the name `wayne_local_emergency_planning` though

**Comment by Brian-Lee** [comment]
Ok. TY

**Comment by saswat01** [comment]
what do you want to scrape ?

**Comment by pjsier** [comment]
Hi @saswat01, we have more info in the [development documentation](https://cityscrapers.org/docs/development/), but this issue is claimed. You're welcome to take a look at any of the other issues that either aren't claimed or have been inactive for the past month or more!

**Comment by pjsier** [comment]
Closed by #863
