### ISSUE TITLE
Spider: Cook County Pharmaceutical Disposal Advisory Committee

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#854]
URL: https://www.cookcountysheriff.org/rx/advisory-committee/
Spider Name: `cook_pharmaceutical_disposal`
Agency Name: Cook County Pharmaceutical Disposal Advisory Committee

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by yuriy-os** [comment]
Can I help with this one?

**Comment by pjsier** [comment]
@yuriy-os go for it! Let me know if you have any questions

**Comment by yuriy-os** [comment]
@pjsier I'm sorry, I can't find enough time to properly work on this issue, feel free to reassign it.

**Comment by glowingrunes** [comment]
Hi, new here and would like to give this a shot for Hacktoberfest!

**Comment by pjsier** [comment]
@glowingrunes sounds good!

**Comment by KilimAnnejaro** [comment]
Hi, could I help out with this issue? Thanks!

**Comment by pjsier** [comment]
@KilimAnnejaro sure! Assigning you now

**Comment by KilimAnnejaro** [comment]
Just want to add a documentation note here: per discussion on Slack, we won't be using OCR to scrape the image at the top of the page. Instead we will be scraping the PDF links below that to get Meeting objects.

**Comment by shf** [comment]
Hi, I would like to take this issue. Thanks.

**Comment by pjsier** [comment]
@shf sounds good! Assigning you now

**Comment by shf** [comment]
@pjsier They are using an image for 2020 meetings, is it Ok to use pytesseract to extract text from the image? users need to install tesseract-ocr for this to run
`sudo apt-get install tesseract-ocr`

**Comment by pjsier** [comment]
@shf OCR is out of scope for what we're doing here, but I think it's still valuable to parse out past meetings in case that changes going forward

**Comment by shf** [comment]
@pjsier the past meetings are also in PDF format, I found you have used pdfminer before in the code, should I continue with that?

**Comment by pjsier** [comment]
I don't think it'll be necessary here since there isn't a lot of information in general, so we're mostly just trying to get dates and links

**Comment by pjsier** [comment]
Closed by #984, thanks @shf!
