### ISSUE TITLE
Spider: Cook County Commission on Human Rights

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#855]
URL: https://www.cookcountyil.gov/agency/commission-human-rights-0
Spider Name: `cook_human_rights`
Agency Name: Cook County Commission on Human Rights

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

This might require scraping some PDFs, so it could be useful to look at [`chi_human_relations`](https://github.com/City-Bureau/city-scrapers/blob/fbddf7cf785f261ea1829706dd58fc7ea5777a9a/city_scrapers/spiders/chi_human_relations.py) for an example of how to handle this

**Comment by infogrrl** [comment]
Hi! I would like to work on this issue.

**Comment by pjsier** [comment]
@infogrrl all yours!

**Comment by rajat641** [comment]
I can work on this. @pjsier can you please assign it to me.

**Comment by pjsier** [comment]
@rajat641 thanks for the interest! We try to limit people to one issue at a time (more info in our [`CONTRIBUTING.md`](https://github.com/City-Bureau/city-scrapers/blob/master/CONTRIBUTING.md)) so let me know which one you'd like to work on first!

**Comment by rajat641** [comment]
Hi @pjsier , It's my first open-source project but I can't find anything available right now. Almost all are 'Claimed'. Please assign me some issue for your choice.

**Comment by pjsier** [comment]
Feel free to grab anything that's marked claimed but hasn't been updated in at least a month. I'll try and do some cleanup of those too

**Comment by jaspsingh** [comment]
Hey @pjsier, I'm interested in helping with this one but it looks like they've posted a "suspension of meetings" notice for the duration of the coronavirus–would this still be available to work on?

**Comment by zahralizadeh** [comment]
Hi, I 'll be happy to help with this issue.

**Comment by pjsier** [comment]
@zahralizadeh sounds good! All yours

**Comment by zahralizadeh** [comment]
@pjsier I am skeptical about the timing of the meetings. The page says that the meetings are held on the second Thursday of every other month, but there is no exact date declared and there is no PDF file that includes the session schedule. Should I automatically extract the second Thursday of every other month using calendar programming? In addition, there is a note of SUSPENSION OF MEETINGS .... what about that?

**Comment by pjsier** [comment]
@zahralizadeh thanks for taking a look at that! Most of the Cook County meetings are on the [events calendar](https://www.cookcountyil.gov/calendar), but due to COVID most are cancelled for the time being. We'll still want to have scrapers set up though for when they do start back up, and you can see there was a meeting on this part of the site in [January](https://www.cookcountyil.gov/calendar-node-field-date/month/2020-01).

The reason we'll still want to scrape the agency page is that it has documents like minutes that aren't always on the event detail page. The setup here should be really similar to [`cook_justice_advisory`](https://github.com/City-Bureau/city-scrapers/blob/main/city_scrapers/spiders/cook_justice_advisory.py) so that would be a good place to start

**Comment by pjsier** [comment]
Closed by #965, thanks @zahralizadeh!
