### ISSUE TITLE
Spider: Detroit Employment Solutions Corporation

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#856]
URL: https://www.descmiworks.com/about-us/public-meetings/
Spider Name: `det_employment_solutions`
Agency Name: Detroit Employment Solutions Corporation

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

Some information will need to be parsed from PDFs, so it could be useful to look at [`chi_human_relations`](https://github.com/City-Bureau/city-scrapers/blob/fbddf7cf785f261ea1829706dd58fc7ea5777a9a/city_scrapers/spiders/chi_human_relations.py) for an example of how to handle this

**Comment by nolanee** [comment]
Hello again! May I work on this issue, since the other one didn't work out?

**Comment by pjsier** [comment]
@nolanee sounds good!

**Comment by dweinzimmer** [comment]
Not sure if there's any particular hacktoberfest issue that would be good to try out for a first time open source contribution -- I'm seeing all of them have comments from folks

**Comment by nolanee** [comment]
@dweinzimmer I was working on this one, but as long as it's okay with @pjsier, feel free to take over. You  can look over what I've done so far, if that helps. I got a little stuck and haven't had much time to make progress on it, but I did get it partially working.

**Comment by dweinzimmer** [comment]
I started working yesterday on #849 just to try it out. If that goes well I will check back in here about this one! Seems like they might be somewhat similar, since that one also requires parsing a PDF.

**Comment by pjsier** [comment]
@dweinzimmer sounds good! Sorry, we're at a shortage of issues at the moment

**Comment by maykonmenezes** [comment]
is there someone working on this?

**Comment by pjsier** [comment]
@maykonmenezes it's been over a month since the last activity, so I'll go ahead and assign you over at the `city-scrapers-det` repo and close this issue
