### ISSUE TITLE
Spider: Chicago Committee on Standards and Tests

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#873]
URL: https://www.chicago.gov/city/en/depts/bldgs/supp_info/committee_on_standardsandtests.html
Spider Name: `chi_standards_tests`
Agency Name: Chicago Committee on Standards and Tests

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by zkunkle** [comment]
I'll work on it

**Comment by travfu** [comment]
I'd like to have a go at this

**Comment by pjsier** [comment]
@travfu all yours!

**Comment by travfu** [comment]
@pjsier this url contains pdfs, are there other spiders that also parse pdf so I can see what dependencies were used instead of adding new ones.

**Comment by pjsier** [comment]
We've been using PyPDF2, but I don't think you need to parse the PDFs here. Since it's rare that they post things in advance, we can verify that the 1:30 time hasn't changed and include a note in `time_notes` to confirm details with the agency

**Comment by pjsier** [comment]
Closed by #926, thanks @travfu!
