### ISSUE TITLE
 Spider: Chicago Special Service Area #8 Lakeview East

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#879]
URL: https://lakevieweast.com/ssa-8/
Spider Name: chi_ssa_8
Agency Name: Chicago Special Service Area #8 Lakeview East

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by h0ffayyy** [comment]
Mind if I take this one?

**Comment by razinc** [comment]
Hi, can I try this?

**Comment by pjsier** [comment]
@razinc all yours!

**Comment by razinc** [comment]
Hi @pjsier. I have a few hiccups & I plan to address those in Slack. How can I get inivation to join the workspace?

**Comment by pjsier** [comment]
@razinc you can fill out this form and we'll add you to the Slack https://airtable.com/shrsdRcYVzp019U22

**Comment by razinc** [comment]
Hi @pjsier. Thanks.

**Comment by benjaminfawcett** [comment]
If there's no progress being made here I'd like to take a stab at it.

**Comment by pjsier** [comment]
@benjaminfawcett feel free to take this one! Saw your comment on the other issue, and we try to have people work on one at a time, but you're welcome to take that one after this is finished

**Comment by JeyRathnam** [comment]
![image](https://user-images.githubusercontent.com/6557230/88696160-8284cf80-d0c8-11ea-9dce-3fcc801a1060.png)
@pjsier Is this the only data we are interested in?

**Comment by pjsier** [comment]
@JeyRathnam we would also want any meeting minutes info. It looks like they haven't posted it for 2020 yet but they have in the past

**Comment by JeyRathnam** [comment]
@pjsier Got it. I am working on getting the dates for now then. 
pytest is returning error : "No module named 'atomicwrites". Is this something on my end? I followed instructions on contribution guide.

**Comment by pjsier** [comment]
@JeyRathnam could you share some more info on your setup? Like which version of Python you're using, whether you're on Windows, or anything else that could be related

**Comment by JeyRathnam** [comment]
@pjsier 
python 3.8.3 
Windows 10 x64

**Comment by JeyRathnam** [comment]
Pytest is failing on test_il_port_district scraper
![image](https://user-images.githubusercontent.com/6557230/89248102-85098c80-d5d4-11ea-85d9-00deab420108.png)

Any ideas?

**Comment by pjsier** [comment]
We've had sporadic issues, but you can ignore that for your PR

**Comment by pjsier** [comment]
Closed by #969, thanks @JeyRathnam!

**Comment by JeyRathnam** [comment]
yay! my first PR!
