### ISSUE TITLE
Spider: Chicago Special Service Area #28 Six Corners

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#906]
URL: https://sixcorners.com/ssa28
Spider Name: chi_ssa_28
Agency Name: Chicago Special Service Area #28 Six Corners

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by codevbus** [comment]
@pjsier - I'll grab this one

**Comment by pjsier** [comment]
Sounds good!

**Comment by pjsier** [comment]
Closed by #921, thanks @codevbus!
