### ISSUE TITLE
Spider: Chicago Special Service Area #50 Calumet Heights/Avalon

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#908]
URL: http://southeastchgochamber.org/special-service-area-50/
Spider Name: chi_ssa_50
Agency Name: Chicago Special Service Area #50 Calumet Heights/Avalon

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by luchiago** [comment]
Hi, I would like to work on that.

**Comment by pjsier** [comment]
@luchiago sounds good!

**Comment by luchiago** [comment]
Hey @pjsier, the URL just have the dates of the meetings. Is that all do I have to extract?

**Comment by pjsier** [comment]
@luchiago yep, that's it! Some of the sites have a lot less information than others

**Comment by pjsier** [comment]
Closed by #923, thanks @luchiago!
