### ISSUE TITLE
Spider: Chicago Special Service Area #64 Walden Parkway

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#909]
URL: https://www.mpbhba.org/business-resources/
Spider Name: chi_ssa_64
Agency Name: Chicago Special Service Area #20 Walden Parkway

Will be identical to #880 except for the specific section

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by dalisaydavid** [comment]
@pjsier I'll take this one too! :)

**Comment by pjsier** [comment]
@dalisaydavid we try to stick to claiming one issue at a time, but after the other one gets merged you're welcome to this one!

**Comment by dalisaydavid** [comment]
Oh, fair enough!

**Comment by TimmyV117** [comment]
@pjsier Mind if I take this?

**Comment by pjsier** [comment]
@TimmyV117 sounds good

**Comment by the-raj** [comment]
@pjsier Could I take a shot at this issue if it is still open? I am already working through the contribution guide.

**Comment by pjsier** [comment]
@the-raj all yours!

**Comment by the-raj** [comment]
@pjsier Hi, I unfortunately couldn't manage to get the scraper code working. Sorry for the late response.

**Comment by DiegoCaraballo** [comment]
Hello @pjsier how are you?
I wish I could contribute to this spider.
Regards, Diego

**Comment by pjsier** [comment]
@DiegoCaraballo all yours! Assigning you now

**Comment by DiegoCaraballo** [comment]
Hello @pjsier This is the area to be extract, right?
![1](https://user-images.githubusercontent.com/21015263/82978033-f7009c80-9fb9-11ea-9615-8af40f7b059f.PNG)

**Comment by pjsier** [comment]
@DiegoCaraballo that's it, but only the section for SSA 20. They haven't updated with the 2020 schedule yet, so we'll want to make sure the year is included in what we're scraping

**Comment by pjsier** [comment]
Closed by #955, thanks @DiegoCaraballo!
