### ISSUE TITLE
Spider: Cook County Emergency Telephone System Board

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#910]
URL: http://www.cookcounty911.com/
Spider Name: cook_emergency_telephone
Agency Name: Cook County Emergency Telephone System Board

We'll need to parse PDFs for this one, and there's an example in [`chi_human_relations`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/chi_human_relations.py)

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by dalisaydavid** [comment]
👋 I'd like to take this one @pjsier!

**Comment by pjsier** [comment]
@dalisaydavid sounds good!

**Comment by cedarfall** [comment]
Is this still being worked on? If not, I'd like to work on it.

**Comment by pjsier** [comment]
It hasn't been active in a while, so it's all yours @cedarfall

**Comment by pjsier** [comment]
Closed by #954, thanks @cedarfall!
