### ISSUE TITLE
Spider: Cook County Justice Advisory Council

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#911]
URL: https://www.cookcountyil.gov/service/justice-advisory-council-meetings
Spider Name: cook_justice_advisory_council
Agency Name: Cook County Justice Advisory Council

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by haworku** [comment]
Hey!  I'm going to try to work on this. Just forked the repo and got things up and running.

**Comment by pjsier** [comment]
@haworku sounds great! This one should be pretty similar to [`cook_board_ethics`](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/cook_board_ethics.py), but we'll also need to pull documents from the main link in the description

**Comment by RebeccaCurry** [comment]
Hi, I'm new to contributing and there's a lot of libraries in this I'm not super familiar with, but I'd like to give this a shot. I know your project is listed as friendly to beginners. Hopefully I won't be putting that too much up to the test!

**Comment by pjsier** [comment]
@RebeccaCurry all yours! Feel free to ask any questions that come up

**Comment by bchao99** [comment]
Hi! It looks like there hasn't been any activity on this issue for the past 30 days so I was wondering if I could work on this.

**Comment by pjsier** [comment]
@bchao99 sounds good!

**Comment by pjsier** [comment]
Closed by #961
