### ISSUE TITLE
Spider: Illinois Arts Council

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#912]
URL: http://www.arts.illinois.gov/about-iac/governance/council-meetings
Spider Name: il_arts_council
Agency Name: Illinois Arts Council
Meeting Name: Agency Board

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by channiemills** [comment]
I'll take this one!

**Comment by pjsier** [comment]
@channiemills sounds good!

**Comment by pjsier** [comment]
Closed by #916
