### ISSUE TITLE
Spider: Illinois Capital Development Board

### ISSUE THREAD

**Issue by pjsier** [City-Bureau/city-scrapers#913]
URL: https://www2.illinois.gov/cdb/about/boardmeetings
Spider Name: il_capital_development
Agency Name: Illinois Capital Development Board

See the [contribution guide](https://cityscrapers.org/docs/development/#contribute) for information on how to get started

**Comment by codevbus** [comment]
@pjsier  - I'd love to take this.

**Comment by pjsier** [comment]
@codevbus all yours!

**Comment by pjsier** [comment]
Closed by #917, thanks @codevbus!
